stages:
  - build

wheel:
  stage: build
  script:
    - python -v
    - python -m pip install setuptools
    - python setup.py bdist_wheel sdist
  tags:
    - gitlab-runner
  artifacts:
    paths:
    - dist
    expire_in: 1 day

pages:
  stage: build
  script:
    - echo 'Nothing to do...'
  tags:
    - gitlab-runner
  artifacts:
    paths:
      - public
  only:
    - master
