stages:
  - build

wheel:
  stage: build
  script: python setup.py bdist_wheel sdist
  artifacts:
    paths:
    - dist/
    expire_in: 1 day

pages:
  script:
    - echo 'Nothing to do...'
  tags:
    - gitlab-runner
  artifacts:
    paths:
      - public
  only:
    - master
