stages:
  - test
  - version
  - deploy

test:
  stage: test
  script:
    - echo "Running tests."
    - bash ~/test_odyssey.sh
  tags:
    - shared
    - merge_requests

version:
  stage: version
  script:
    - echo "Checking version"
    - bash ~/check_version.sh
  only:
    - master
  tags:
    - shared

deploy:
  stage: deploy
  script:
    - echo "Deploying update."
    - bash ~/dev_odyssey.sh
  only:
    - master
  tags:
    - shared