FROM python:3.6

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

RUN apt update
RUN apt install -y libpq-dev python3-dev build-essential libpango-1.0-0 libpangocairo-1.0-0

COPY ./ /usr/src/app
RUN pip install requests
RUN pip install -r requirements.txt

CMD ["pytest", "--cov=odyssey", "tests/"]