-- dietitian reasons
INSERT INTO "LookupVisitReasons" ("reason","role_id") 
VALUES
('Basic Food/Nutrition Education', 5),
('Men''s Health', 5),
('Women''s Health', 5),
('Sports Nutrition', 5),
('Kidney Issues', 5),
('Peri/Post Menopausal', 5),
('Mindful/Intuitive Eating', 5),
('Immune Support', 5),
('Stress Management', 5),
('Hormonal Concerns', 5),
('Chronic Fatigue', 5),
('Digestive Complaints', 5),
('PCOS', 5),
('Improve Relationship with Food', 5),
('Eating Disorder', 5),
('Weight Loss', 5),
('Sleep Better', 5),
('Increase Energy', 5),
('Improve Heart Health', 5),
('Longevity', 5),
('Become More Active', 5),
('Lower Blood Pressure', 5),
('Lower Cholesterol', 5),
('Lower Blood Sugar', 5),
('Improve Metabolic Health', 5),
('Improve Overall Health and Wellness', 5);


-- therapist reasons
INSERT INTO "LookupVisitReasons" ("reason","role_id") 
VALUES
('Addiction', 7),
('Stress Management', 7),
('Confidence/Self-Esteem', 7),
('Depression', 7),
('Grief and Loss', 7),
('Phobias', 7),
('Relationships', 7),
('Trauma and PTSD', 7),
('Transitions and Goals', 7), 
('Specific Mental Health Diagnosis', 7),
('Women''s Health', 7),
('Men''s Health', 7),
('Eating Disorder', 7),
('Hormonal Concerns', 7),
('Chronic Fatigue', 7),
('Improve Relationship with Food', 7),
('Weight Loss', 7),
('Sleep Better', 7),
('Increase Energy', 7),
('Longevity', 7),
('Become More Active', 7),
('Lower Blood Pressure', 7),
('Improve Overall Health and Wellness', 7),
('Need Someone To Talk To', 7);


-- trainer reasons
INSERT INTO "LookupVisitReasons" ("reason","role_id") 
VALUES
('Improve Cardio', 14),
('Core and Balance', 14),
('Corrective Exercise', 14),
('Flexibility and Mobility', 14),
('Injury Mitigation', 14),
('Increase Muscle Mass/Get Toned', 14),
('Improve Posture', 14),
('Stress Management', 14),
('Increase Strength', 14),
('Sport Specific Training', 14),
('Women''s Health', 14),
('Men''s Health', 14),
('Weight Loss', 14),
('Sleep Better', 14),
('Increase Energy', 14),
('Improve Heart Health', 14),
('Longevity', 14),
('Become More Active', 14),
('Lower Blood Pressure', 14),
('Lower Cholesterol', 14),
('Lower Blood Sugar', 14),
('Improve Metabolic Health', 14),
('Improve Overall Health and Wellness', 14);


-- med doc reasons
INSERT INTO "LookupVisitReasons" ("reason","role_id") 
VALUES
('Acne', 13),
('Allergies', 13),
('Anemia', 13),
('Anxiety', 13),
('Arthritic Pain', 13),
('Asthma', 13),
('Bronchitis', 13),
('Cellulitis', 13),
('Chronic Cough', 13),
('Cold Sores', 13),
('Colds and Flu', 13),
('Conjunctivitis/Pink Eye', 13),
('Depression', 13),
('Diabetes', 13),
('Diarrhea', 13),
('Fatigue', 13),
('Flu Symptoms', 13),
('Hyperlipidemia (high cholesterol)', 13),
('Hypertension', 13),
('Hypothyroidism', 13),
('Insect Bite(s)', 13),
('Nausea', 13),
('Pharyngitis', 13),
('Prescription Refills (not-controlled)', 13),
('Rashes', 13),
('Respiratory Infection', 13),
('Sinus Infection', 13),
('Skin Inflammation', 13),
('Sore Throat', 13),
('Tobacco Cessation', 13),
('Urinary Tract Infection', 13),
('Low Vitamin D', 13),
('General Wellness', 13),
('None Of The Above', 13);