
UPDATE "LookupTerritoriesOfOperations"
  SET active = true
  where idx = 1;

INSERT INTO "LookupTerritoriesOfOperations" ("sub_territory_abbreviation", "sub_territory", "active", "country_id") 
VALUES
('AL','Alabama',false, 1),
('AK','Alaska',false, 1),
('AZ','Arizona',false, 1),
('AR','Arkansas',false, 1),
('CA','California',false, 1),
('CO','Colorado',false, 1),
('CT','Connecticut',false, 1),
('DE','Delaware',false, 1),
('GA','Georgia',false, 1),
('HI','Hawaii',false, 1),
('ID','Idaho',false, 1),
('IL','Illinois',false, 1),
('IN','Indiana',false, 1),
('IA','Iowa',false, 1),
('KS','Kansas',false, 1),
('KY','Kentucky',false, 1),
('LA','Louisiana',false, 1),
('ME','Maine',false, 1),
('MD','Maryland',false, 1),
('MA','Massachusetts',false, 1),
('MI','Michigan',false, 1),
('MN','Minnesota',false, 1),
('MS','Mississippi',false, 1),
('MO','Missouri',false, 1),
('MT','Montana',false, 1),
('NE','Nebraska',false, 1),
('NV','Nevada',false, 1),
('NH','New Hampshire',false, 1),
('NJ','New Jersey',false, 1),
('NM','New Mexico',false, 1),
('NY','New York',false, 1),
('NC','North Carolina',false, 1),
('ND','North Dakota',false, 1),
('OH','Ohio',false, 1),
('OK','Oklahoma',false, 1),
('OR','Oregon',false, 1),
('PY','Pennsylvania',false, 1),
('RI','Rhode Island',false, 1),
('SC','South Carolina',false, 1),
('SD','South Dakota',false, 1),
('TN','Tennessee',false, 1),
('TX','Texas',false, 1),
('UT','Utah',false, 1),
('VT','Vermont',false, 1),
('VA','Virginia',false, 1),
('WA','Washington',false, 1),
('WV','West Virginia',false, 1),
('WI','Wisconsin',false, 1),
('WY','Wyoming',false, 1);