INSERT INTO "LookupSTDs" ("std_id","std") 
VALUES 
(1,'Chancroid'),
(2,'Chlamydia'),
(3,'Crabs (Pubic Lice)'),
(4,'Gonorrhea'),
(5,'Hepatitis'),
(6,'Herpes'),
(7,'HIV/AIDS'),
(8,'Human Papillomavirus and Genital Warts'),
(9,'Lymphogranuloma Venereum'),
(10,'Molluscum Contagiosum'),
(11,'Nongonococcal Urethritis'),
(12,'Pelvic Inflammatory Disease'),
(13,'Scabies'),
(14,'Syphilis'),
(15,'Trichomoniasis'),
(16,'Vaginal Yeast Infection'),
(17,'Bacterial Vaginosis'),
(18,'Yeast Infection in Men'),
(19,'Balanitis'),
(20,'Cytomegalovirus'),
(21,'Mycoplasma'),
(22,'Mononucleosis');