"""
Database tables for supporting lookup tables. These tables should be static tables only used for reference,
not to be edited at runtime. 
"""
from sqlalchemy import UniqueConstraint

from odyssey import db
from odyssey.utils.constants import DB_SERVER_TIME
from odyssey.utils.base.models import BaseModel

class SystemTelehealthSessionCosts(BaseModel):
    """ Teleheath session costs that can be changed by a system administrator
    """

    __table_args__ = (UniqueConstraint('country', 'profession_type', name='telehealth_costs_unique_resource_country_profession'),)

    cost_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    """
    The autogenerated ID of this cost.

    :type: integer, primary key, autoincrementing
    """

    currency_id = db.Column(db.Integer, db.ForeignKey('LookupCurrencies.idx'), nullable=False)
    """
    ID of the currency type.

    :type: intger, foreign key(LookupCurrencies.idx)
    """

    profession_type = db.Column(db.String, nullable=False)
    """
    Name of the profression associated with this cost. Must be one of the ACCESS_ROLES.

    :type: string
    """

    session_cost = db.Column(db.Numeric(10,2), nullable=False)
    """
    Cost of this teleheatlh session in this country's currency.

    :type: Numeric
    """

    session_min_cost = db.Column(db.Numeric(10,2), nullable=False)
    """
    Minimum cost allowed of this teleheatlh session in this country's currency.

    :type: Numeric
    """
    
    session_max_cost = db.Column(db.Numeric(10,2), nullable=False)
    """
    Maximum cost allowed of this teleheatlh session in this country's currency.

    :type: Numeric
    """

class SystemVariables(db.Model):
    """ Holds various system-wide variables that can be viewed and edited by the sys_admin.
        The value is always stored as a string and will need to be cast into its proper type where used.
    """

    __tablename__ = 'SystemVariables'

    created_at = db.Column(db.DateTime, default=DB_SERVER_TIME)
    """
    Creation timestamp of this row in the database.

    :type: :class:`datetime.datetime`
    """

    updated_at = db.Column(db.DateTime, default=DB_SERVER_TIME, onupdate=DB_SERVER_TIME)
    """
    Last update timestamp of this row in the database.

    :type: :class:`datetime.datetime`
    """

    var_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    """
    Id of this variable.

    :type: int, primary key, autoincrementing
    """

    var_name = db.Column(db.String)
    """
    Name of this variable.

    :type: string
    """
    
    var_value = db.Column(db.String)
    """
    Current value of this variable. Must be stored as a string and cast to the needed type in code.

    :type: string
    """