
-----------------------------
-- Empty table and reset index. 
-- Rather than altering the table, this script inserts data 
-- So to avoid duplicates, we empty the table and reindex.
-- This is a solution that should be run only once on 
-- persistent databases. 
-- Further changes to this table will be done through the API
-----------------------------




DO $$
DECLARE
  x integer;
  query varchar := 'select count(*) from "MedicalConditions"';
BEGIN 
execute query into x;
  IF x >= 1 THEN
   execute 
   		'delete from "MedicalConditions" 
			where medical_condition_id >= 1;
		alter sequence "MedicalConditions_medical_condition_id_seq"
			restart with 1;';
  END IF;
END $$;

INSERT INTO "MedicalConditions" ("category", "subcategory", "condition") 
VALUES 
('Autoimmune',null,'Diabetes type 1'),
('Autoimmune',null,'Diabetes type 2'),
('Autoimmune',null,'Low blood sugar/hypoglycemia'),
('Autoimmune','Thyroid','Graves'),
('Autoimmune','Thyroid','Hashimoto'),
('Autoimmune','Thyroid','Hyperthyroid'),
('Autoimmune','Thyroid','Hypothyroid'),
('Autoimmune','Adrenal','Cushings'),
('Autoimmune','Adrenal','Addisons'),
('Autoimmune',null,'Thymic disease'),
('Autoimmune',null,'Multiple endocrine neoplasia (MEN) 1'),
('Autoimmune',null,'Multiple endocrine neoplasia (MEN) 2'),
('Autoimmune',null,'Rheumatoid disease'),
('Autoimmune',null,'Sjögrens disease'),
('Autoimmune',null,'Systemic lupus erythematosus'),
('Autoimmune',null,'Psoriatic disease'),
('Autoimmune',null,'Fibromyalgia'),
('Autoimmune',null,'Autoimmune vasculitis'),
('Autoimmune',null,'Gout'),
('Autoimmune',null,'Amyloidosis'),
('Autoimmune',null,'Sarcoidosis'),
('Autoimmune',null,'Scleroderma'),
('Cancer',null,'Brain'),
('Cancer',null,'Bone'),
('Cancer','Blood','Leukemia'),
('Cancer','Blood','Lymphoma'),
('Cancer','Gut','Esophageal'),
('Cancer','Gut','Stomach'),
('Cancer','Gut','Colorectal'),
('Cancer','Gut','Liver'),
('Cancer','Gut','Pancreatic'),
('Cancer','Lung','Small cell'),
('Cancer','Lung','Non-small cell'),
('Cancer','Kidney','Renal Cell'),
('Cancer','Kidney','Urothelial carcinoma (transitional cell)'),
('Cancer','Urological','Bladder'),
('Cancer','Urological','Penile'),
('Cancer','Urological','Prostatic'),
('Cancer',null,'Breast'),
('Cancer','Gynecological','Cervical/ovarian'),
('Cancer','Gynecological','Uterine'),
('Cancer','Gynecological','Vaginal'),
('Cancer','Skin','Melanoma'),
('Cancer','Skin','Basal cell carcinoma'),
('Cancer','Skin','Squamous cell carcinoma'),
('Cardiovascular',null,'High blood pressure (hypertension)'),
('Cardiovascular',null,'Heart attack/myocardial infarction (MI)'),
('Cardiovascular',null,'Congestive heart failure'),
('Cardiovascular',null,'Hypertrophic cardiomyopathy'),
('Cardiovascular','Heart valvular disease','Aortic'),
('Cardiovascular','Heart valvular disease','Pulmonic'),
('Cardiovascular','Heart valvular disease','Mitral'),
('Cardiovascular','Heart valvular disease','Tricuspid'),
('Cardiovascular',null,'Heart murmur'),
('Cardiovascular',null,'Aneurysm (aortic, or other blood vessels)'),
('Cardiovascular','Bleeding disorder','Hemophilia A'),
('Cardiovascular','Bleeding disorder','Hemophilia B'),
('Cardiovascular','Bleeding disorder','Von Willebrands disease'),
('Cardiovascular','Bleeding disorder','Rare clotting factor deficiencies'),
('Cardiovascular','Blood clots/deep venous thrombosis','Provoked'),
('Cardiovascular','Blood clots/deep venous thrombosis','Spontaneous'),
('Cardiovascular','Anemia','Iron deficiency'),
('Cardiovascular','Anemia','Blood loss'),
('Cardiovascular','Anemia','Thalassemia'),
('Cardiovascular','Anemia','Sickle cell'),
('Cardiovascular','Anemia','Hemolytic'),
('Cardiovascular','Anemia','Aplastic (or other bone marrow disease)'),
('Cardiovascular','Anemia','Megaloblastic (vitamin B12/folate deficiency)'),
('Cardiovascular','Anemia','Pernicious'),
('Cardiovascular','Chest pain/angina','Stable'),
('Cardiovascular','Chest pain/angina','Unstable'),
('Cardiovascular','Heart arrhythmia','Atrial fibrillation'),
('Cardiovascular','Heart arrhythmia','Atrial flutter'),
('Cardiovascular','Heart arrhythmia','Wolfe-Parkinson white'),
('Cardiovascular','Heart arrhythmia','Paroxysmal supraventricular tachycardia'),
('Cardiovascular','Heart arrhythmia','Ventricular tachycardia'),
('Cardiovascular','Heart arrhythmia','Ventricular fibrillation'),
('Cardiovascular','Heart arrhythmia','Torsades de pointes'),
('Cardiovascular','Heart arrhythmia','Premature heartbeat'),
('Cardiovascular','Heart arrhythmia','Bradycardia'),
('Cardiovascular',null,'Pericarditis'),
('Cardiovascular',null,'High cholesterol/hyperlipidemia'),
('Cardiovascular',null,'Splenic disorder'),
('Cardiovascular',null,'CABG/bypass surgery'),
('Cardiovascular',null,'Pacemaker/defibrillator'),
('Cardiovascular',null,'Vascular stents'),
('Dermatological',null,'Acne'),
('Dermatological',null,'Rosacea'),
('Dermatological',null,'Hives/urticaria'),
('Dermatological',null,'Eczema/atopic dermatitis'),
('Dermatological',null,'Alopecia'),
('Dermatological',null,'Hirsutism'),
('Dermatological',null,'Hyperhidrosis'),
('Dermatological',null,'Hidradenitis suppurativa'),
('Dermatological',null,'Vitiligo'),
('Dermatological',null,'Keratosis pilaris'),
('Dermatological',null,'Fungal nail infection'),
('Gastrointestinal','Inflammatory bowel disease','Crohns disease'),
('Gastrointestinal','Inflammatory bowel disease','Ulcerative colitis'),
('Gastrointestinal',null,'Irritable bowel syndrome'),
('Gastrointestinal',null,'Celiac disease'),
('Gastrointestinal',null,'GERD/gastritis'),
('Gastrointestinal','Ulcer','Stomach'),
('Gastrointestinal','Ulcer','Small intestine (duodenal, jejunum, ileum)'),
('Gastrointestinal','Ulcer','Large intestine'),
('Gastrointestinal',null,'Frequent loose stools'),
('Gastrointestinal',null,'Frequent constipation'),
('Gastrointestinal',null,'Hiatal hernia'),
('Gastrointestinal',null,'Swallowing dysfunction'),
('Gastrointestinal',null,'Liver disorder'),
('Gastrointestinal',null,'Gallbladder disease'),
('Gastrointestinal',null,'Diverticulitis (infection)'),
('Gastrointestinal',null,'Diverticulosis'),
('Gastrointestinal',null,'Zenkers diverticula'),
('Gastrointestinal',null,'Nutritional deficiency'),
('Gastrointestinal',null,'Food allergies'),
('Gastrointestinal',null,'Pancreatic disease'),
('Gastrointestinal',null,'Rectal disease'),
('Infectious disease',null,'Hepatitis A'),
('Infectious disease',null,'Hepatitis B'),
('Infectious disease',null,'Hepatitis C'),
('Infectious disease',null,'HIV/AIDS'),
('Infectious disease',null,'Tuberculosis'),
('Infectious disease',null,'Influenza A or B'),
('Infectious disease',null,'COVID-19'),
('Infectious disease',null,'Staph infection'),
('Infectious disease',null,'Norovirus'),
('Infectious disease',null,'Shigellosis'),
('Infectious disease',null,'Salmonella'),
('Infectious disease',null,'Chicken pox (varicella zoster)'),
('Infectious disease',null,'Shingles (herpes zoster)'),
('Infectious disease',null,'Measles'),
('Infectious disease',null,'Mumps'),
('Infectious disease',null,'Rubella'),
('Infectious disease',null,'Meningitis'),
('Infectious disease',null,'Polio'),
('Infectious disease',null,'Lyme disease'),
('Infectious disease',null,'Rocky mountain spotted fever'),
('Infectious disease',null,'Diphtheria'),
('Infectious disease',null,'Pertussis'),
('Infectious disease',null,'Toxic shock syndrome'),
('Infectious disease',null,'Tetanus'),
('Infectious disease',null,'Malaria'),
('Infectious disease',null,'Infectious mononucleosis'),
('Infectious disease',null,'E. coli'),
('Infectious disease',null,'Giardiasis'),
('Musculoskeletal',null,'Osteoarthritis'),
('Musculoskeletal',null,'Osteoporosis'),
('Musculoskeletal',null,'Osteopenia'),
('Musculoskeletal',null,'Osteomalacia'),
('Musculoskeletal','History of fractures','Stress'),
('Musculoskeletal','History of fractures','Compression'),
('Musculoskeletal','History of fractures','Comminuted'),
('Musculoskeletal','History of fractures','Segmental'),
('Musculoskeletal','History of fractures','Spiral'),
('Musculoskeletal','History of fractures','Transverse'),
('Musculoskeletal','History of fractures','Oblique'),
('Musculoskeletal','History of fractures','Greenstick'),
('Musculoskeletal','History of fractures','Open/compound'),
('Musculoskeletal',null,'Closed'),
('Musculoskeletal',null,'Dislocation'),
('Musculoskeletal',null,'Torn ligament/meniscus/tendon'),
('Musculoskeletal',null,'Torn muscle'),
('Musculoskeletal',null,'Bone spur'),
('Musculoskeletal',null,'Inguinal hernia'),
('Nephrological',null,'Chronic kidney disease'),
('Nephrological',null,'Acute kidney failure/injury'),
('Nephrological',null,'Pyelonephritis (kidney infection)'),
('Nephrological',null,'Nephrolithiasis (kidney stones)'),
('Nephrological',null,'Hydronephrosis'),
('Nephrological',null,'Polycystic kidney disease'),
('Nephrological',null,'Nephrotic syndrome'),
('Nephrological',null,'Nephritic syndrome'),
('Neurological',null,'Headaches/migraines'),
('Neurological',null,'Blackouts'),
('Neurological',null,'Dizziness/vertigo'),
('Neurological',null,'History of fall(s)'),
('Neurological',null,'Balance disturbance'),
('Neurological',null,'Vision loss'),
('Neurological',null,'Hearing loss'),
('Neurological',null,'Insomnia'),
('Neurological',null,'Traumatic head/brain injury'),
('Neurological',null,'Stroke/transient ischemic attack (TIA)'),
('Neurological',null,'Multiple sclerosis'),
('Neurological',null,'Peripheral neuropathy'),
('Neurological',null,'Guillain barre'),
('Neurological',null,'Myasthenia gravis'),
('Neurological',null,'Epilepsy/seizure disorder'),
('Neurological',null,'Parkinsons'),
('Neurological',null,'Alzheimers dementia'),
('Neurological',null,'Lewy body dementia'),
('Neurological',null,'Other dementia or memory loss'),
('Neurological',null,'Spinal cord disease (disc herniation/bulging)'),
('Neurological',null,'Vertebral fracture or fusion'),
('Neurological',null,'Brain aneurysm'),
('Neurological',null,'Pituitary disease'),
('Neurological',null,'Hypothalamus disease'),
('Neurological',null,'Carpal tunnel'),
('Neurological',null,'Spinal stenosis'),
('Neurological',null,'Sciatica'),
('Neurological',null,'Spondylolisthesis'),
('Obstetrical/gynecological',null,'Uterine fibroids'),
('Obstetrical/gynecological',null,'Abnormal pap smear (cervical dysplasia)'),
('Obstetrical/gynecological',null,'Dysmenorrhea'),
('Obstetrical/gynecological',null,'Oligomenorrhea'),
('Obstetrical/gynecological',null,'Amenorrhea'),
('Obstetrical/gynecological',null,'Dysfunctional uterine bleeding (heavy or prolonged)'),
('Obstetrical/gynecological',null,'Metrorrhagia (too frequent periods)'),
('Obstetrical/gynecological',null,'Menorrhagia (heavy periods)'),
('Obstetrical/gynecological',null,'Premenstrual syndrome'),
('Obstetrical/gynecological',null,'Premenstrual dysmorphic disorder'),
('Obstetrical/gynecological',null,'Endometriosis'),
('Obstetrical/gynecological',null,'Polycystic ovarian syndrome'),
('Obstetrical/gynecological',null,'Ovarian cysts'),
('Obstetrical/gynecological',null,'Endometrial hyperplasia'),
('Obstetrical/gynecological',null,'Pelvic pain'),
('Obstetrical/gynecological',null,'Pelvic inflammatory disease'),
('Obstetrical/gynecological',null,'Pain with sex (dyspareunia)'),
('Obstetrical/gynecological',null,'Preeclampsia'),
('Obstetrical/gynecological',null,'Eclampsia'),
('Obstetrical/gynecological',null,'Ectopic pregnancy'),
('Obstetrical/gynecological',null,'Gestational diabetes'),
('Obstetrical/gynecological',null,'Gestational hypertension'),
('Obstetrical/gynecological',null,'Lichen planus'),
('Obstetrical/gynecological',null,'Lichen sclerosis'),
('Obstetrical/gynecological',null,'Perimenopause'),
('Obstetrical/gynecological',null,'Post menopause'),
('Obstetrical/gynecological',null,'Placenta accreta'),
('Obstetrical/gynecological',null,'Placenta previa'),
('Pulmonological',null,'Asthma'),
('Pulmonological',null,'Emphysema/COPD'),
('Pulmonological',null,'Pneumonia'),
('Pulmonological',null,'Chronic bronchitis'),
('Pulmonological',null,'Allergies'),
('Pulmonological',null,'Sleep apnea'),
('Pulmonological',null,'Deviated septum'),
('Pulmonological',null,'Shortness of breath'),
('Pulmonological',null,'Interstitial lung disease'),
('Pulmonological',null,'Pneumothorax'),
('Pulmonological',null,'Atelectasis'),
('Pulmonological',null,'Pulmonary embolus'),
('Pulmonological',null,'Pulmonary hypertension'),
('Pulmonological',null,'Pulmonary edema'),
('Pulmonological',null,'Pleural effusion'),
('Pulmonological',null,'Cystic fibrosis/bronchiectasis'),
('Pulmonological',null,'Acute respiratory distress syndrome (ARDS)'),
('Pulmonological',null,'Pneumoconiosis'),
('Pulmonological',null,'Mesothelioma'),
('Surgery',null,'Cardiac'),
('Surgery',null,'Breast'),
('Surgery',null,'Heart'),
('Surgery',null,'Cosmetic'),
('Surgery',null,'Dermatological'),
('Surgery',null,'Ears, nose, throat'),
('Surgery',null,'Gastrointestinal'),
('Surgery',null,'Neurological'),
('Surgery',null,'OB-GYN'),
('Surgery',null,'Ophthalmic'),
('Surgery',null,'Orthopedic'),
('Surgery',null,'Pulmonological'),
('Surgery',null,'Urological'),
('Surgery',null,'Vascular'),
('Trauma',null,'Concussion'),
('Trauma',null,'Traumatic brain injury'),
('Trauma',null,'Motor vehicle accident'),
('Trauma',null,'Whiplash'),
('Trauma',null,'Gun shot wound'),
('Trauma',null,'Amputation'),
('Urological',null,'Urinary tract infection'),
('Urological',null,'Urinary incontinence'),
('Urological',null,'Bladder prolapse'),
('Urological',null,'Interstitial cystitis (painful bladder syndrome)'),
('Urological',null,'Overactive bladder'),
('Urological',null,'Erectile dysfunction'),
('Urological',null,'Prostate disease'),
('Urological',null,'Vasectomy');