delete from "LookupEmergencyNumbers" 
			where idx >= 1;
alter sequence "LookupEmergencyNumbers_idx_seq"
  restart with 1;

INSERT INTO "LookupEmergencyNumbers" ("continent","code","country","service","phone_number") 
VALUES
('North America', 'BM', 'Bermuda', 'Ambulance', '911'),
('North America', 'BM',  'Bermuda', 'Police', '911'),
('North America', 'BM',  'Bermuda', 'Fire', '911'),
('North America', 'CA',  'Canada', 'Ambulance', '911'),
('North America', 'CA',  'Canada', 'Police', '911'),
('North America', 'CA',  'Canada', 'Fire', '911'),
('North America', 'MX',  'Mexico', 'Ambulance', '911'),
('North America', 'MX',  'Mexico', 'Police', '911'),
('North America', 'MX',  'Mexico', 'Fire', '911'),
('North America', 'PM',  'Saint Pierre and Miquelon', 'Ambulance', '112'),
('North America', 'PM',  'Saint Pierre and Miquelon', 'Police', '112'),
('North America', 'PM',  'Saint Pierre and Miquelon', 'Fire', '112'),
('North America', 'US',  'United States of America', 'Ambulance', '911'),
('North America', 'US',  'United States of America', 'Police', '911'),
('North America', 'US',  'United States of America', 'Fire', '911'),
('Europe', 'CY',  'Akrotiri and Dhekelia', 'Ambulance', '112'),
('Europe', 'CY',  'Akrotiri and Dhekelia', 'Police', '112'),
('Europe', 'CY',  'Akrotiri and Dhekelia', 'Fire', '112'),
('Europe', 'CY',  'Akrotiri and Dhekelia', 'Ambulance', '999'),
('Europe', 'CY',  'Akrotiri and Dhekelia', 'Police', '999'),
('Europe', 'CY',  'Akrotiri and Dhekelia', 'Fire', '999'),
('Europe', 'AX',  'Aland Islands', 'Ambulance', '112'),
('Europe', 'AX',  'Aland Islands', 'Police', '112'),
('Europe', 'AX',  'Aland Islands', 'Fire', '112'),
('Europe', 'AL',  'Albania', 'Ambulance', '127'),
('Europe', 'AL',  'Albania', 'Police', '129'),
('Europe', 'AL',  'Albania', 'Fire', '128'),
('Europe', 'AD',  'Andorra', 'Ambulance', '116'),
('Europe', 'AD',  'Andorra', 'Police', '110'),
('Europe', 'AD',  'Andorra', 'Fire', '118'),
('Europe', 'AM',  'Armenia', 'Ambulance', '112'),
('Europe', 'AM',  'Armenia', 'Police', '112'),
('Europe', 'AM',  'Armenia', 'Fire', '112'),
('Europe', 'AM',  'Armenia', 'Ambulance', '911'),
('Europe', 'AM',  'Armenia', 'Police', '911'),
('Europe', 'AM',  'Armenia', 'Fire', '911'),
('Europe', 'AT',  'Austria', 'Ambulance', '144'),
('Europe', 'AT',  'Austria', 'Police', '112'),
('Europe', 'AT',  'Austria', 'Police', '133'),
('Europe', 'AT',  'Austria', 'Fire', '122'),
('Europe', 'AZ',  'Azerbaijan', 'Ambulance', '103'),
('Europe', 'AZ',  'Azerbaijan', 'Police', '102'),
('Europe', 'AZ',  'Azerbaijan', 'Fire', '101'),
('Europe', 'BY',  'Belarus', 'Police', '102'),
('Europe', 'BY',  'Belarus', 'Ambulance', '103'),
('Europe', 'BY',  'Belarus', 'Fire', '101'),
('Europe', 'BE',  'Belgium', 'Police', '101'),
('Europe', 'BE',  'Belgium', 'Ambulance', '112'),
('Europe', 'BE',  'Belgium', 'Fire', '112'),
('Europe', 'BA',  'Bosnia and Herzegovina', 'Police', '122'),
('Europe', 'BA',  'Bosnia and Herzegovina', 'Ambulance', '124'),
('Europe', 'BA',  'Bosnia and Herzegovina', 'Fire', '123'),
('Europe', 'BG',  'Bulgaria', 'Police', '112'),
('Europe', 'BG',  'Bulgaria', 'Police', '166'),
('Europe', 'BG',  'Bulgaria', 'Ambulance', '112'),
('Europe', 'BG',  'Bulgaria', 'Ambulance', '150'),
('Europe', 'BG',  'Bulgaria', 'Fire', '112'),
('Europe', 'BG',  'Bulgaria', 'Fire', '160'),
('Europe', 'HR',  'Croatia', 'Police', '112'),
('Europe', 'HR',  'Croatia', 'Police', '192'),
('Europe', 'HR',  'Croatia', 'Ambulance', '112'),
('Europe', 'HR',  'Croatia', 'Ambulance', '194'),
('Europe', 'HR',  'Croatia', 'Fire', '112'),
('Europe', 'HR',  'Croatia', 'Fire', '193'),
('Europe', 'CY',  'Cyprus', 'Police', '112'),
('Europe', 'CY',  'Cyprus', 'Police', '199'),
('Europe', 'CY',  'Cyprus', 'Ambulance', '112'),
('Europe', 'CY',  'Cyprus', 'Ambulance', '199'),
('Europe', 'CY',  'Cyprus', 'Fire', '112'),
('Europe', 'CY',  'Cyprus', 'Fire', '199'),
('Europe', 'CZ',  'Czech Republic', 'Police', '112'),
('Europe', 'CZ',  'Czech Republic', 'Police', '158'),
('Europe', 'CZ',  'Czech Republic', 'Ambulance', '112'),
('Europe', 'CZ',  'Czech Republic', 'Ambulance', '155'),
('Europe', 'CZ',  'Czech Republic', 'Fire', '112'),
('Europe', 'CZ',  'Czech Republic', 'Fire', '150'),
('Europe', 'DK',  'Denmark', 'Police', '112'),
('Europe', 'DK',  'Denmark', 'Ambulance', '112'),
('Europe', 'DK',  'Denmark', 'Fire', '112'),
('Europe', 'EE',  'Estonia', 'Police', '112'),
('Europe', 'EE',  'Estonia', 'Ambulance', '112'),
('Europe', 'EE',  'Estonia', 'Fire', '112'),
('Europe', 'FO',  'Faroe Islands', 'Police', '112'),
('Europe', 'FO',  'Faroe Islands', 'Ambulance', '112'),
('Europe', 'FO',  'Faroe Islands', 'Fire', '112'),
('Europe', 'FI',  'Finland', 'Police', '112'),
('Europe', 'FI',  'Finland', 'Ambulance', '112'),
('Europe', 'FI',  'Finland', 'Fire', '112'),
('Europe', 'FR',  'France', 'Police', '112'),
('Europe', 'FR',  'France', 'Police', '17'),
('Europe', 'FR',  'France', 'Ambulance', '112'),
('Europe', 'FR',  'France', 'Ambulance', '15'),
('Europe', 'FR',  'France', 'Fire', '112'),
('Europe', 'FR',  'France', 'Fire', '18'),
('Europe', 'GE',  'Georgia', 'Police', '112'),
('Europe', 'GE',  'Georgia', 'Ambulance', '112'),
('Europe', 'GE',  'Georgia', 'Fire', '112'),
('Europe', 'DE',  'Germany', 'Police', '110'),
('Europe', 'DE',  'Germany', 'Ambulance', '112'),
('Europe', 'DE',  'Germany', 'Fire', '112'),
('Europe', 'GI',  'Gibraltar', 'Police', '199'),
('Europe', 'GI',  'Gibraltar', 'Police', '112'),
('Europe', 'GI',  'Gibraltar', 'Police', '999'),
('Europe', 'GI',  'Gibraltar', 'Ambulance', '190'),
('Europe', 'GI',  'Gibraltar', 'Ambulance', '112'),
('Europe', 'GI',  'Gibraltar', 'Ambulance', '999'),
('Europe', 'GI',  'Gibraltar', 'Fire', '190'),
('Europe', 'GI',  'Gibraltar', 'Fire', '112'),
('Europe', 'GI',  'Gibraltar', 'Fire', '999'),
('Europe', 'GR', 'Greece', 'Police', '100'),
('Europe', 'GR', 'Greece', 'Ambulance', '166'),
('Europe', 'GR', 'Greece', 'Fire', '199'),
('Europe', 'GL', 'Greenland', 'Police', '112'),
('Europe', 'GL', 'Greenland', 'Ambulance', '112'),
('Europe', 'GL', 'Greenland', 'Fire', '112'),
('Europe', 'GG', 'Guernsey', 'Police', '112'),
('Europe', 'GG', 'Guernsey', 'Ambulance', '112'),
('Europe', 'GG', 'Guernsey', 'Fire', '112'),
('Europe', 'GG', 'Guernsey', 'Police', '999'),
('Europe', 'GG', 'Guernsey', 'Ambulance', '999'),
('Europe', 'GG', 'Guernsey', 'Fire', '999'),
('Europe', 'HU', 'Hungary', 'Police', '112'),
('Europe', 'HU', 'Hungary', 'Police', '107'),
('Europe', 'HU', 'Hungary', 'Ambulance', '112'),
('Europe', 'HU', 'Hungary', 'Ambulance', '104'),
('Europe', 'HU', 'Hungary', 'Fire', '112'),
('Europe', 'HU', 'Hungary', 'Fire', '105'),
('Europe', 'IS', 'Iceland', 'Police', '112'),
('Europe', 'IS', 'Iceland', 'Ambulance', '112'),
('Europe', 'IS', 'Iceland', 'Fire', '112'),
('Europe', 'IE', 'Ireland', 'Police', '112'),
('Europe', 'IE', 'Ireland', 'Police', '999'),
('Europe', 'IE', 'Ireland', 'Ambulance', '112'),
('Europe', 'IE', 'Ireland', 'Ambulance', '999'),
('Europe', 'IE', 'Ireland', 'Fire', '112'),
('Europe', 'IE', 'Ireland', 'Fire', '999'),
('Europe', 'IM', 'Isle of Man', 'Police', '112'),
('Europe', 'IM', 'Isle of Man', 'Police', '999'),
('Europe', 'IM', 'Isle of Man', 'Ambulance', '112'),
('Europe', 'IM', 'Isle of Man', 'Ambulance', '999'),
('Europe', 'IM', 'Isle of Man', 'Fire', '112'),
('Europe', 'IM', 'Isle of Man', 'Fire', '999'),
('Europe', 'IT	', 'Italy', 'Police', '112'),
('Europe', 'IT	', 'Italy', 'Ambulance', '112'),
('Europe', 'IT	', 'Italy', 'Fire', '112'),
('Europe', 'JE', 'Jersey', 'Police', '112'),
('Europe', 'JE', 'Jersey', 'Police', '999'),
('Europe', 'JE', 'Jersey', 'Ambulance', '112'),
('Europe', 'JE', 'Jersey', 'Ambulance', '999'),
('Europe', 'JE', 'Jersey', 'Fire', '112'),
('Europe', 'JE', 'Jersey', 'Fire', '999'),
('Europe', 'XK', 'Kosovo', 'Police', '192'),
('Europe', 'XK', 'Kosovo', 'Ambulance', '194'),
('Europe', 'XK', 'Kosovo', 'Fire', '193'),
('Europe', 'LV', 'Latvia', 'Police', '112'),
('Europe', 'LV', 'Latvia', 'Ambulance', '112'),
('Europe', 'LV', 'Latvia', 'Fire', '112'),
('Europe', 'LT', 'Lithuania', 'Police', '112'),
('Europe', 'LT', 'Lithuania', 'Ambulance', '112'),
('Europe', 'LT', 'Lithuania', 'Fire', '112'),
('Europe', 'LI', 'Liechtenstein', 'Police', '117'),
('Europe', 'LI', 'Liechtenstein', 'Ambulance', '144'),
('Europe', 'LI', 'Liechtenstein', 'Fire', '118'),
('Europe', 'LU', 'Luxembourg', 'Police', '112'),
('Europe', 'LU', 'Luxembourg', 'Ambulance', '112'),
('Europe', 'LU', 'Luxembourg', 'Fire', '112'),
('Europe', 'MK', 'Republic of North Macedonia', 'Police', '192'),
('Europe', 'MK', 'Republic of North Macedonia', 'Ambulance', '194'),
('Europe', 'MK', 'Republic of North Macedonia', 'Fire', '193'),
('Europe', 'MT', 'Malta', 'Police', '112'),
('Europe', 'MT', 'Malta', 'Ambulance', '112'),
('Europe', 'MT', 'Malta', 'Fire', '112'),
('Europe', 'MD', 'Moldova', 'Police', '112'),
('Europe', 'MD', 'Moldova', 'Ambulance', '112'),
('Europe', 'MD', 'Moldova', 'Fire', '112'),
('Europe', 'MC', 'Monaco', 'Police', '17'),
('Europe', 'MC', 'Monaco', 'Ambulance', '15'),
('Europe', 'MC', 'Monaco', 'Fire', '18'),
('Europe', 'ME', 'Montenegro', 'Police', '122'),
('Europe', 'ME', 'Montenegro', 'Ambulance', '124'),
('Europe', 'ME', 'Montenegro', 'Fire', '123'),
('Europe', 'NL', 'Netherlands', 'Police', '112'),
('Europe', 'NL', 'Netherlands', 'Ambulance', '112'),
('Europe', 'NL', 'Netherlands', 'Fire', '112'),
('Europe', 'CY', 'Northern Cyprus', 'Police', '112'),
('Europe', 'CY', 'Northern Cyprus', 'Ambulance', '112'),
('Europe', 'CY', 'Northern Cyprus', 'Fire', '112'),
('Europe', 'NO', 'Norway', 'Police', '112'),
('Europe', 'NO', 'Norway', 'Ambulance', '113'),
('Europe', 'NO', 'Norway', 'Fire', '110'),
('Europe', 'PL', 'Poland', 'Police', '112'),
('Europe', 'PL', 'Poland', 'Police', '997'),
('Europe', 'PL', 'Poland', 'Ambulance', '112'),
('Europe', 'PL', 'Poland', 'Ambulance', '999'),
('Europe', 'PL', 'Poland', 'Fire', '112'),
('Europe', 'PL', 'Poland', 'Fire', '998'),
('Europe', 'PT', 'Portugal', 'Police', '112'),
('Europe', 'PT', 'Portugal', 'Ambulance', '112'),
('Europe', 'PT', 'Portugal', 'Fire', '112'),
('Europe', 'RO', 'Romania', 'Police', '112'),
('Europe', 'RO', 'Romania', 'Ambulance', '112'),
('Europe', 'RO', 'Romania', 'Fire', '112'),
('Europe', 'RU', 'Russia', 'Police', '112'),
('Europe', 'RU', 'Russia', 'Police', '102'),
('Europe', 'RU', 'Russia', 'Ambulance', '112'),
('Europe', 'RU', 'Russia', 'Ambulance', '103'),
('Europe', 'RU', 'Russia', 'Fire', '112'),
('Europe', 'RU', 'Russia', 'Fire', '101'),
('Europe', 'SM', 'San Marino', 'Police', '113'),
('Europe', 'SM', 'San Marino', 'Ambulance', '118'),
('Europe', 'SM', 'San Marino', 'Fire', '115'),
('Europe', 'RS', 'Serbia', 'Police', '112'),
('Europe', 'RS', 'Serbia', 'Police', '192'),
('Europe', 'RS', 'Serbia', 'Ambulance', '194'),
('Europe', 'RS', 'Serbia', 'Fire', '193'),
('Europe', 'SK', 'Slovakia', 'Police', '158'),
('Europe', 'SK', 'Slovakia', 'Ambulance', '155'),
('Europe', 'SK', 'Slovakia', 'Fire', '150'),
('Europe', 'SI', 'Slovenia', 'Police', '112'),
('Europe', 'SI', 'Slovenia', 'Ambulance', '112'),
('Europe', 'SI', 'Slovenia', 'Fire', '112'),
('Europe', 'ES', 'Spain', 'Police', '112'),
('Europe', 'ES', 'Spain', 'Ambulance', '112'),
('Europe', 'ES', 'Spain', 'Fire', '112'),
('Europe', 'SE', 'Sweden', 'Police', '112'),
('Europe', 'SE', 'Sweden', 'Ambulance', '112'),
('Europe', 'SE', 'Sweden', 'Fire', '112'),
('Europe', 'CH', 'Switzerland', 'Police', '117'),
('Europe', 'CH', 'Switzerland', 'Ambulance', '144'),
('Europe', 'CH', 'Switzerland', 'Fire', '118'),
('Europe', 'TR', 'Turkey', 'Police', '112'),
('Europe', 'TR', 'Turkey', 'Ambulance', '112'),
('Europe', 'TR', 'Turkey', 'Fire', '112'),
('Europe', 'UA', 'Ukraine', 'Police', '102'),
('Europe', 'UA', 'Ukraine', 'Ambulance', '103'),
('Europe', 'UA', 'Ukraine', 'Fire', '101'),
('Europe', 'GB', 'United Kingdom', 'Police', '112'),
('Europe', 'GB', 'United Kingdom', 'Police', '999'),
('Europe', 'GB', 'United Kingdom', 'Ambulance', '112'),
('Europe', 'GB', 'United Kingdom', 'Ambulance', '999'),
('Europe', 'GB', 'United Kingdom', 'Fire', '112'),
('Europe', 'GB', 'United Kingdom', 'Fire', '999'),
('Europe', 'VA', 'Vatican City', 'Police', '112'),
('Europe', 'VA', 'Vatican City', 'Ambulance', '112'),
('Europe', 'VA', 'Vatican City', 'Fire', '112');