from odyssey import db

class MedicalHistory(db.Model):

    __tablename__ = 'MedicalHistory'

    idx = db.Column(db.Integer, primary_key=True, autoincrement=True)
    clientid = db.Column(db.Integer, db.ForeignKey('ClientInfo.clientid'), nullable=False)

    last_examination_date = db.Column(db.Date)
    last_examination_reason = db.Column(db.String(1024))

    goals = db.Column(db.Text)
    concerns = db.Column(db.Text)
    family_history = db.Column(db.Text)
    social_history = db.Column(db.Text)
    allergies = db.Column(db.Text)
    medication = db.Column(db.Text)

    diagnostic_xray = db.Column(db.String(1024))
    diagnostic_ctscan = db.Column(db.String(1024))
    diagnostic_endoscopy = db.Column(db.String(1024))
    diagnostic_mri = db.Column(db.String(1024))
    diagnostic_ultrasound = db.Column(db.String(1024))
    diagnostic_other = db.Column(db.String(1024))

    general_headaches = db.Column(db.String(1024))
    general_blackouts = db.Column(db.String(1024))
    general_vertigo = db.Column(db.String(1024))
    general_sinus = db.Column(db.String(1024))
    general_falling = db.Column(db.String(1024))
    general_balance = db.Column(db.String(1024))
    general_vision = db.Column(db.String(1024))
    general_hearing = db.Column(db.String(1024))
    general_memory = db.Column(db.String(1024))
    general_insomnia = db.Column(db.String(1024))
    general_other = db.Column(db.String(1024))

    blood_bloodpressure = db.Column(db.String(1024))
    blood_heartattack = db.Column(db.String(1024))
    blood_heartdissease = db.Column(db.String(1024))
    blood_congestive = db.Column(db.String(1024))
    blood_aneurysm = db.Column(db.String(1024))
    blood_bleeding = db.Column(db.String(1024))
    blood_bloodclots = db.Column(db.String(1024))
    blood_anemia = db.Column(db.String(1024))
    blood_chestpain = db.Column(db.String(1024))
    blood_arrythmia = db.Column(db.String(1024))
    blood_cholesterol = db.Column(db.String(1024))
    blood_other = db.Column(db.String(1024))

    digestive_irritablebowel = db.Column(db.String(1024))
    digestive_crohns = db.Column(db.String(1024))
    digestive_celiac = db.Column(db.String(1024))
    digestive_reflux = db.Column(db.String(1024))
    digestive_ulcer = db.Column(db.String(1024))
    digestive_loosestool = db.Column(db.String(1024))
    digestive_constipation = db.Column(db.String(1024))
    digestive_eatingdiscomfort = db.Column(db.String(1024))
    digestive_hiatalhernia = db.Column(db.String(1024))
    digestive_swallowing = db.Column(db.String(1024))
    digestive_liver = db.Column(db.String(1024))
    digestive_other = db.Column(db.String(1024))

    skeletal_arthritis = db.Column(db.String(1024))
    skeletal_fractures = db.Column(db.String(1024))
    skeletal_compressionfracture = db.Column(db.String(1024))
    skeletal_stressfracture = db.Column(db.String(1024))
    skeletal_dislocation = db.Column(db.String(1024))
    skeletal_inguinalhernia = db.Column(db.String(1024))
    skeletal_otherhernia = db.Column(db.String(1024))
    skeletal_diastatis = db.Column(db.String(1024))
    skeletal_carpaltunnel = db.Column(db.String(1024))
    skeletal_thoracicoutlet = db.Column(db.String(1024))
    skeletal_spinalstenosis = db.Column(db.String(1024))
    skeletal_sciatica = db.Column(db.String(1024))
    skeletal_spondylolisthesis = db.Column(db.String(1024))
    skeletal_dischernia = db.Column(db.String(1024))
    skeletal_temporomandibular = db.Column(db.String(1024))
    skeletal_other = db.Column(db.String(1024))

    immune_diabetes = db.Column(db.String(1024))
    immune_lowbloodsugar = db.Column(db.String(1024))
    immune_hepatitis = db.Column(db.String(1024))
    immune_hiv = db.Column(db.String(1024))
    immune_tuberculosis = db.Column(db.String(1024))
    immune_cancer = db.Column(db.String(1024))
    immune_thyroid = db.Column(db.String(1024))
    immune_autoimmune = db.Column(db.String(1024))
    immune_osteoporosis = db.Column(db.String(1024))
    immune_gout = db.Column(db.String(1024))
    immune_rheuma = db.Column(db.String(1024))
    immune_lupus = db.Column(db.String(1024))
    immune_fibromyalgia = db.Column(db.String(1024))
    immune_other = db.Column(db.String(1024))

    surgery_bypass = db.Column(db.String(1024))
    surgery_pacemaker = db.Column(db.String(1024))
    surgery_stents = db.Column(db.String(1024))
    surgery_abdominal = db.Column(db.String(1024))
    surgery_gastric = db.Column(db.String(1024))
    surgery_hysterectomy = db.Column(db.String(1024))
    surgery_tuballigation = db.Column(db.String(1024))
    surgery_laparoscopy = db.Column(db.String(1024))
    surgery_bladder = db.Column(db.String(1024))
    surgery_csection = db.Column(db.String(1024))
    surgery_hernia = db.Column(db.String(1024))
    surgery_gallbladder = db.Column(db.String(1024))
    surgery_orthopedic = db.Column(db.String(1024))
    surgery_back = db.Column(db.String(1024))
    surgery_plastic = db.Column(db.String(1024))
    surgery_other = db.Column(db.String(1024))

    uro_urological = db.Column(db.String(1024))
    uro_kidney = db.Column(db.String(1024))
    uro_incontinence = db.Column(db.String(1024))
    uro_endometriosis = db.Column(db.String(1024))
    uro_gynecology = db.Column(db.String(1024))
    uro_fibroids = db.Column(db.String(1024))
    uro_childbirth = db.Column(db.String(1024))
    uro_other = db.Column(db.String(1024))

    respiratory_smoke = db.Column(db.String(1024))
    respiratory_asthma = db.Column(db.String(1024))
    respiratory_emphysema = db.Column(db.String(1024))
    respiratory_pneumonia = db.Column(db.String(1024))
    respiratory_allergies = db.Column(db.String(1024))
    respiratory_sleepapnea = db.Column(db.String(1024))
    respiratory_deviatedseptum = db.Column(db.String(1024))
    respiratory_shortbreath = db.Column(db.String(1024))
    respiratory_other = db.Column(db.String(1024))

    neuro_brain = db.Column(db.String(1024))
    neuro_stroke = db.Column(db.String(1024))
    neuro_ms = db.Column(db.String(1024))
    neuro_neuropathy = db.Column(db.String(1024))
    neuro_epilepsy = db.Column(db.String(1024))
    neuro_parkinson = db.Column(db.String(1024))
    neuro_neuromuscular = db.Column(db.String(1024))
    neuro_other = db.Column(db.String(1024))

    trauma_whiplash = db.Column(db.String(1024))
    trauma_accident = db.Column(db.String(1024))
    trauma_concussion = db.Column(db.String(1024))
    trauma_other = db.Column(db.String(1024))

    nutrition_deficiency = db.Column(db.String(1024))
    nutrition_allergies = db.Column(db.String(1024))
    nutrition_eating = db.Column(db.String(1024))
    nutrition_other = db.Column(db.String(1024))
