"""Add user biological sex

Revision ID: 04ea7e0894a4
Revises: f67acff421f8
Create Date: 2020-11-18 13:46:36.550129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ea7e0894a4'
down_revision = '48526617897a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('biologoical_sex_male', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'biologoical_sex_male')
    # ### end Alembic commands ###
