"""Changed ClientRemovalRequests table to UserRemovalRequest

Revision ID: 0e0b2fb1fdf8
Revises: 48526617897a
Create Date: 2020-12-03 10:26:27.042519

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e0b2fb1fdf8'
down_revision = '48526617897a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserRemovalRequests',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.drop_table('ClientRemovalRequests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClientRemovalRequests',
    sa.Column('idx', sa.INTEGER(), server_default=sa.text('nextval(\'"ClientRemovalRequests_idx_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='ClientRemovalRequests_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx', name='ClientRemovalRequests_pkey')
    )
    op.drop_table('UserRemovalRequests')
    # ### end Alembic commands ###
