"""changed thb variables from int to floats

Revision ID: 181802f48ef7
Revises: c629447e4622
Create Date: 2020-10-21 17:39:35.932728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '181802f48ef7'
down_revision = 'c629447e4622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TrainerMoxyAssessment', 'starting_thb',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'performance_baseline_thb',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'performance_thb_1',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'performance_thb_2',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'performance_thb_3',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'performance_thb_4',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'recovery_baseline_thb',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'recovery_thb_1',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'recovery_thb_2',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'recovery_thb_3',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'recovery_thb_4',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'thb_tank_size',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TrainerMoxyRipTest', 'thb_tank_size',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'recovery_thb_4',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'recovery_thb_3',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'recovery_thb_2',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'recovery_thb_1',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'recovery_baseline_thb',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'performance_thb_4',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'performance_thb_3',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'performance_thb_2',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'performance_thb_1',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyRipTest', 'performance_baseline_thb',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('TrainerMoxyAssessment', 'starting_thb',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
