"""medical institutes tables

Revision ID: 21aad6fa547d
Revises: 90b2d6c84344
Create Date: 2020-08-18 16:21:02.903237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21aad6fa547d'
down_revision = '90b2d6c84344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MedicalInstitutions',
    sa.Column('institute_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('institute_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('institute_id'),
    sa.UniqueConstraint('institute_name')
    )
    op.create_table('ClientExternalMR',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('med_record_id', sa.String(), nullable=False),
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='ClientExternalMR_clientid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institute_id'], ['MedicalInstitutions.institute_id'], name='ClientExternalMR_institute_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx'),
    sa.UniqueConstraint('clientid', 'med_record_id', 'institute_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClientExternalMR')
    op.drop_table('MedicalInstitutions')
    # ### end Alembic commands ###
