"""client removal request table

Revision ID: 2300d2b3ad4c
Revises: 3ea30db69377
Create Date: 2020-07-28 13:23:45.771843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2300d2b3ad4c'
down_revision = '3ea30db69377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_removal_requests',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staffid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staffid'], ['Staff.staffid'], name='ClientRemovalRequests_staffid_fkey'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_removal_requests')
    # ### end Alembic commands ###
