"""add access roles to staff table

Revision ID: 26a4bf5df204
Revises: 946d90e85ca3
Create Date: 2020-06-22 17:05:52.336125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a4bf5df204'
down_revision = '946d90e85ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Staff', sa.Column('is_system_admin', sa.Boolean(), nullable=False, server_default='False'))
    op.add_column('Staff', sa.Column('access_role', sa.String(), nullable=False, server_default='cs'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Staff', 'access_role')
    op.drop_column('Staff', 'is_system_admin')
    # ### end Alembic commands ###
