"""moxy, heart assessment update

Revision ID: 2c861c33474f
Revises: ab8cbaeda195
Create Date: 2020-08-26 12:20:05.829513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c861c33474f'
down_revision = 'ab8cbaeda195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PTChessboard', 'co2_tolerance')
    op.add_column('TrainerHeartAssessment', sa.Column('co2_tolerance', sa.Integer(), nullable=True))
    op.add_column('TrainerMoxyAssessment', sa.Column('vl_side', sa.String(), nullable=True))
    op.add_column('TrainerMoxyRipTest', sa.Column('vl_side', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrainerMoxyRipTest', 'vl_side')
    op.drop_column('TrainerMoxyAssessment', 'vl_side')
    op.drop_column('TrainerHeartAssessment', 'co2_tolerance')
    op.add_column('PTChessboard', sa.Column('co2_tolerance', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
