"""Create Medical Imaging Table

Revision ID: 329b6d8fb16b
Revises: 9b92a2be034e
Create Date: 2020-09-29 18:02:55.530935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329b6d8fb16b'
down_revision = '9b92a2be034e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MedicalImaging',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('image_date', sa.Date(), nullable=True),
    sa.Column('image_type', sa.String(length=1024), nullable=True),
    sa.Column('image_read', sa.Text(), nullable=True),
    sa.Column('image_origin_location', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('image_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MedicalImaging')
    # ### end Alembic commands ###
