"""add lookupSubscriptions table

Revision ID: 34b7750b4fac
Revises: ac16cd39251f
Create Date: 2021-01-27 16:19:12.100109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b7750b4fac'
down_revision = 'ac16cd39251f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LookupNotifications',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notification_type', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('background_color', sa.String(), nullable=True),
    sa.Column('symbol_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LookupNotifications')
    # ### end Alembic commands ###
