"""add record locator id to clientinfo

Revision ID: 3cb25c724f84
Revises: 9887fc6db28e
Create Date: 2020-09-23 10:59:35.165625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb25c724f84'
down_revision = '9887fc6db28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClientInfo', sa.Column('record_locator_id', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClientInfo', 'record_locator_id')
    # ### end Alembic commands ###
