"""add cascade delete to every table

Revision ID: 3ea30db69377
Revises: 6388fde942e3
Create Date: 2020-07-28 12:36:16.200067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ea30db69377'
down_revision = '6388fde942e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heart_assessment')
    op.drop_table('movement_assessment')
    op.drop_table('moxy_assessment')
    op.drop_table('lung_assessment')
    op.drop_table('moxy_rip_test')
    op.drop_table('chessboard')
    op.drop_table('strength_assessment')
    op.drop_table('power_assessment')
    op.drop_constraint('ClientConsent_clientid_fkey', 'ClientConsent', type_='foreignkey')
    op.create_foreign_key('ClientConsent_clientid_fkey', 'ClientConsent', 'ClientInfo', ['clientid'], ['clientid'], ondelete='CASCADE')
    op.drop_constraint('ClientConsultContract_clientid_fkey', 'ClientConsultContract', type_='foreignkey')
    op.create_foreign_key('ClientColusultContract_clientid_fkey', 'ClientConsultContract', 'ClientInfo', ['clientid'], ['clientid'], ondelete='CASCADE')
    op.drop_constraint('ClientIndividualContract_clientid_fkey', 'ClientIndividualContract', type_='foreignkey')
    op.create_foreign_key('ClientIndividualContract_clientid_fkey', 'ClientIndividualContract', 'ClientInfo', ['clientid'], ['clientid'], ondelete='CASCADE')
    op.drop_constraint('ClientPolicies_clientid_fkey', 'ClientPolicies', type_='foreignkey')
    op.create_foreign_key('ClientPolicies_clientid_fkey', 'ClientPolicies', 'ClientInfo', ['clientid'], ['clientid'], ondelete='CASCADE')
    op.drop_constraint('ClientRelease_clientid_fkey', 'ClientRelease', type_='foreignkey')
    op.create_foreign_key('ClientRelease_clientid_fkey', 'ClientRelease', 'ClientInfo', ['clientid'], ['clientid'], ondelete='CASCADE')
    op.drop_constraint('ClientSubscriptionContract_clientid_fkey', 'ClientSubscriptionContract', type_='foreignkey')
    op.create_foreign_key('ClientSubscriptionContract_clientid_fkey', 'ClientSubscriptionContract', 'ClientInfo', ['clientid'], ['clientid'], ondelete='CASCADE')
    op.drop_constraint('MedicalHistory_clientid_fkey', 'MedicalHistory', type_='foreignkey')
    op.create_foreign_key('MedicalHistory_clientid_fkey', 'MedicalHistory', 'ClientInfo', ['clientid'], ['clientid'], ondelete='CASCADE')
    op.drop_constraint('MedicalPhysicalExam_clientid_fkey', 'MedicalPhysicalExam', type_='foreignkey')
    op.create_foreign_key('MedicalPhysicalExam_clientid_fkey', 'MedicalPhysicalExam', 'ClientInfo', ['clientid'], ['clientid'], ondelete='CASCADE')
    op.drop_constraint('PTHistory_clientid_fkey', 'PTHistory', type_='foreignkey')
    op.create_foreign_key('PTHistory_clientid_fkey', 'PTHistory', 'ClientInfo', ['clientid'], ['clientid'], ondelete='CASCADE')
    op.drop_constraint('remote_registration_clientid_fkey', 'remote_registration', type_='foreignkey')
    op.create_foreign_key('remote_registration_clientid_fkey', 'remote_registration', 'ClientInfo', ['clientid'], ['clientid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('remote_registration_clientid_fkey', 'remote_registration', type_='foreignkey')
    op.create_foreign_key('remote_registration_clientid_fkey', 'remote_registration', 'ClientInfo', ['clientid'], ['clientid'])
    op.drop_constraint('PTHistory_clientid_fkey', 'PTHistory', type_='foreignkey')
    op.create_foreign_key('PTHistory_clientid_fkey', 'PTHistory', 'ClientInfo', ['clientid'], ['clientid'])
    op.drop_constraint('MedicalPhysicalExam_clientid_fkey', 'MedicalPhysicalExam', type_='foreignkey')
    op.create_foreign_key('MedicalPhysicalExam_clientid_fkey', 'MedicalPhysicalExam', 'ClientInfo', ['clientid'], ['clientid'])
    op.drop_constraint('MedicalHistory_clientid_fkey', 'MedicalHistory', type_='foreignkey')
    op.create_foreign_key('MedicalHistory_clientid_fkey', 'MedicalHistory', 'ClientInfo', ['clientid'], ['clientid'])
    op.drop_constraint('ClientSubscriptionContract_clientid_fkey', 'ClientSubscriptionContract', type_='foreignkey')
    op.create_foreign_key('ClientSubscriptionContract_clientid_fkey', 'ClientSubscriptionContract', 'ClientInfo', ['clientid'], ['clientid'])
    op.drop_constraint('ClientRelease_clientid_fkey', 'ClientRelease', type_='foreignkey')
    op.create_foreign_key('ClientRelease_clientid_fkey', 'ClientRelease', 'ClientInfo', ['clientid'], ['clientid'])
    op.drop_constraint('ClientPolicies_clientid_fkey', 'ClientPolicies', type_='foreignkey')
    op.create_foreign_key('ClientPolicies_clientid_fkey', 'ClientPolicies', 'ClientInfo', ['clientid'], ['clientid'])
    op.drop_constraint('ClientIndividualContract_clientid_fkey', 'ClientIndividualContract', type_='foreignkey')
    op.create_foreign_key('ClientIndividualContract_clientid_fkey', 'ClientIndividualContract', 'ClientInfo', ['clientid'], ['clientid'])
    op.drop_constraint('ClientColusultContract_clientid_fkey', 'ClientConsultContract', type_='foreignkey')
    op.create_foreign_key('ClientConsultContract_clientid_fkey', 'ClientConsultContract', 'ClientInfo', ['clientid'], ['clientid'])
    op.drop_constraint('ClientConsent_clientid_fkey', 'ClientConsent', type_='foreignkey')
    op.create_foreign_key('ClientConsent_clientid_fkey', 'ClientConsent', 'ClientInfo', ['clientid'], ['clientid'])
    op.create_table('power_assessment',
    sa.Column('idx', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('clientid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('keiser_upper_r_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_upper_r_attempt_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_upper_r_attempt_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_upper_r_attempt_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_upper_l_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_upper_l_attempt_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_upper_l_attempt_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_upper_l_attempt_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_bi_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_bi_attempt_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_bi_attempt_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_bi_attempt_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_r_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_r_attempt_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_r_attempt_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_r_attempt_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_l_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_l_attempt_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_l_attempt_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keiser_lower_l_attempt_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_watts_per_kg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lower_watts_per_kg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='power_assessment_clientid_fkey'),
    sa.PrimaryKeyConstraint('idx', name='power_assessment_pkey')
    )
    op.create_table('strength_assessment',
    sa.Column('idx', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('clientid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('upper_push_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('upper_push_l_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_l_attempt_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_l_attempt_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_l_attempt_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_l_estimated_10rm', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upper_push_r_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_r_attempt_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_r_attempt_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_r_attempt_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_r_estimated_10rm', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upper_push_bi_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_bi_attempt_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_bi_attempt_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_bi_attempt_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_push_bi_estimated_10rm', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upper_pull_l_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_l_attempt_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_l_attempt_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_l_attempt_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_l_estimated_10rm', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upper_pull_r_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_r_attempt_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_r_attempt_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_r_attempt_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_r_estimated_10rm', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('upper_pull_bi_weight', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_bi_attempt_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_bi_attempt_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_bi_attempt_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upper_pull_bi_estimated_10rm', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='strength_assessment_clientid_fkey'),
    sa.PrimaryKeyConstraint('idx', name='strength_assessment_pkey')
    )
    op.create_table('chessboard',
    sa.Column('idx', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('isa_right', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isa_left', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('isa_structure', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('isa_dynamic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('left_shoulder_er', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_shoulder_ir', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_shoulder_abd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_shoulder_add', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_shoulder_flexion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_shoulder_extension', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_shoulder_er', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_shoulder_ir', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_shoulder_abd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_shoulder_add', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_shoulder_flexion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_shoulder_extension', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_hip_slr', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_hip_er', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_hip_ir', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_hip_abd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_hip_add', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_hip_flexion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('left_hip_extension', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_hip_er', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_hip_ir', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_hip_abd', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_hip_add', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_hip_flexion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_hip_extension', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('right_hip_slr', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='chessboard_clientid_fkey'),
    sa.PrimaryKeyConstraint('idx', name='chessboard_pkey')
    )
    op.create_table('moxy_rip_test',
    sa.Column('idx', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('clientid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('performance_smo2_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_thb_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_average_power_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_hr_max_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_smo2_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_thb_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_average_power_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_hr_max_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_smo2_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_thb_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_average_power_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_hr_max_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_smo2_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_thb_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_average_power_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_hr_max_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_smo2_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_thb_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_average_power_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_hr_min_1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_smo2_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_thb_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_average_power_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_hr_min_2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_smo2_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_thb_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_average_power_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_hr_min_3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_smo2_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_thb_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_average_power_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_hr_min_4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('smo2_tank_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('thb_tank_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_baseline_smo2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_baseline_thb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_baseline_smo2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recovery_baseline_thb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_watt_kg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_interval_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_recovery_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limiter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('intervention', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='moxy_rip_test_clientid_fkey'),
    sa.PrimaryKeyConstraint('idx', name='moxy_rip_test_pkey')
    )
    op.create_table('lung_assessment',
    sa.Column('idx', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('clientid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bag_size', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('breaths_per_minute', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_minute_volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('liters_min_kg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='lung_assessment_clientid_fkey'),
    sa.PrimaryKeyConstraint('idx', name='lung_assessment_pkey')
    )
    op.create_table('moxy_assessment',
    sa.Column('idx', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('clientid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recovery_baseline', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_baseline', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gas_tank_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('starting_sm_o2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('starting_thb', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('limiter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('intervention', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('performance_metric_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('performance_metric_1_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('performance_metric_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('performance_metric_2_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='moxy_assessment_clientid_fkey'),
    sa.PrimaryKeyConstraint('idx', name='moxy_assessment_pkey')
    )
    op.create_table('movement_assessment',
    sa.Column('idx', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('clientid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('squat_dept', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('squat_ramp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('squat_eye_test', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('squat_can_breathe', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('squat_can_look_up', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('toe_touch_depth', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('toe_touch_pelvis_movement', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('toe_touch_ribcage_movement', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('toe_touch_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('standing_rotation_r_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('standing_rotation_l_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='movement_assessment_clientid_fkey'),
    sa.PrimaryKeyConstraint('idx', name='movement_assessment_pkey')
    )
    op.create_table('heart_assessment',
    sa.Column('idx', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('clientid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resting_hr', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_hr', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('theoretical_max_hr', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_eval_hr', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_training_hr', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_vo2_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='heart_assessment_clientid_fkey'),
    sa.PrimaryKeyConstraint('idx', name='heart_assessment_pkey')
    )
    # ### end Alembic commands ###
