"""new table to facilitate remote registration

Revision ID: 41333abdd3da
Revises: 26a4bf5df204
Create Date: 2020-06-26 15:31:42.487393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41333abdd3da'
down_revision = '26a4bf5df204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remote_registration',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('registration_portal_id', sa.String(length=32), nullable=True),
    sa.Column('registration_portal_expiration', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_index(op.f('ix_remote_registration_registration_portal_id'), 'remote_registration', ['registration_portal_id'], unique=True)
    op.create_index(op.f('ix_remote_registration_token'), 'remote_registration', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remote_registration_token'), table_name='remote_registration')
    op.drop_index(op.f('ix_remote_registration_registration_portal_id'), table_name='remote_registration')
    op.drop_table('remote_registration')
    # ### end Alembic commands ###
