"""Add availability exceptions table

Revision ID: 5ddda1e5f73a
Revises: c3854ec8f9ee
Create Date: 2022-03-22 16:29:48.667150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddda1e5f73a'
down_revision = 'c3854ec8f9ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TelehealthStaffAvailabilityExceptions',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('exception_booking_window_id_start_time', sa.Integer(), nullable=False),
    sa.Column('exception_booking_window_id_end_time', sa.Integer(), nullable=False),
    sa.Column('is_busy', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exception_booking_window_id_end_time'], ['LookupBookingTimeIncrements.idx'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exception_booking_window_id_start_time'], ['LookupBookingTimeIncrements.idx'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.alter_column('User', 'was_staff',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'was_staff',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('TelehealthStaffAvailabilityExceptions')
    # ### end Alembic commands ###
