"""Add FreeStyle CGM table.

Revision ID: 625fb2a459b0
Revises: 8dd3ed610f45
Create Date: 2020-10-06 09:38:46.235765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '625fb2a459b0'
down_revision = '8dd3ed610f45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WearablesFreeStyle',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('timestamps', postgresql.ARRAY(sa.DateTime(), dimensions=1), nullable=True),
    sa.Column('glucose', postgresql.ARRAY(sa.Float(), dimensions=1), nullable=True),
    sa.Column('activation_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )

    # This is a manual addition. Cannot update existing table with data
    # and add a boolean column with nullable = False. Throws error:
    #   sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation)
    #   column "has_freestyle" contains null values
    op.add_column('Wearables', sa.Column('has_freestyle', sa.Boolean(), default=False, nullable=True))
    op.execute('UPDATE "Wearables" SET has_freestyle = false')
    op.alter_column('Wearables', 'has_freestyle', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Wearables', 'has_freestyle')
    op.alter_column('MobilityAssessment', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('WearablesFreeStyle')
    # ### end Alembic commands ###
