"""Add PDF SHA1 hash

Revision ID: 6388fde942e3
Revises: 66f24111759d
Create Date: 2020-07-13 13:40:31.182787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6388fde942e3'
down_revision = '66f24111759d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClientConsent', sa.Column('pdf_hash', sa.String(length=40), nullable=True))
    op.add_column('ClientConsultContract', sa.Column('pdf_hash', sa.String(length=40), nullable=True))
    op.add_column('ClientIndividualContract', sa.Column('pdf_hash', sa.String(length=40), nullable=True))
    op.add_column('ClientPolicies', sa.Column('pdf_hash', sa.String(length=40), nullable=True))
    op.add_column('ClientRelease', sa.Column('pdf_hash', sa.String(length=40), nullable=True))
    op.add_column('ClientSubscriptionContract', sa.Column('pdf_hash', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClientSubscriptionContract', 'pdf_hash')
    op.drop_column('ClientRelease', 'pdf_hash')
    op.drop_column('ClientPolicies', 'pdf_hash')
    op.drop_column('ClientIndividualContract', 'pdf_hash')
    op.drop_column('ClientConsultContract', 'pdf_hash')
    op.drop_column('ClientConsent', 'pdf_hash')
    # ### end Alembic commands ###
