"""created tables for medical general history endpoint

Revision ID: 65f48672909f
Revises: 40e57e2da26a
Create Date: 2020-11-25 10:15:33.776520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '65f48672909f'
down_revision = 'e2b7f6857eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MedicalGeneralInfo',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary_doctor_contact_name', sa.String(length=50), nullable=True),
    sa.Column('primary_doctor_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('primary_doctor_contact_email', sa.String(), nullable=True),
    sa.Column('blood_type', sa.String(), nullable=True),
    sa.Column('blood_type_positive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('MedicalGeneralInfoMedicationAllergy',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.String(), nullable=True),
    sa.Column('allergy_symptoms', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('MedicalGeneralInfoMedications',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medication_name', sa.Text(), nullable=True),
    sa.Column('medication_dosage', sa.Float(), nullable=True),
    sa.Column('medication_units', sa.String(), nullable=True),
    sa.Column('medication_freq', sa.Integer(), nullable=True),
    sa.Column('medication_times_per_freq', sa.Integer(), nullable=True),
    sa.Column('medication_time_units', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MedicalGeneralInfoMedications')
    op.drop_table('MedicalGeneralInfoMedicationAllergy')
    op.drop_table('MedicalGeneralInfo')
    # ### end Alembic commands ###
