"""added unique field to user_id and added last_smoke and last_smoke_time column to MedicalSocialHistory

Revision ID: 6d6c668f16ae
Revises: 65f48672909f
Create Date: 2020-12-17 02:28:17.100371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d6c668f16ae'
down_revision = '65f48672909f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MedicalSocialHistory', sa.Column('ever_smoked', sa.Boolean(), nullable=True))
    op.add_column('MedicalSocialHistory', sa.Column('last_smoke', sa.Integer(), nullable=True))
    op.add_column('MedicalSocialHistory', sa.Column('last_smoke_time', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'UserLogin', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserLogin', type_='unique')
    op.drop_column('MedicalSocialHistory', 'ever_smoked')
    op.drop_column('MedicalSocialHistory', 'last_smoke_time')
    op.drop_column('MedicalSocialHistory', 'last_smoke')
    # ### end Alembic commands ###
