"""Add user table

Revision ID: 6da9644cc376
Revises: f400f854d46d
Create Date: 2020-10-12 16:33:13.604806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6da9644cc376'
down_revision = 'f400f854d46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('publicid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=True),
    sa.Column('staffid', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staffid'], ['Staff.staffid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('publicid')
    )
    op.create_index(op.f('ix_User_token'), 'User', ['token'], unique=True)
    op.drop_constraint('Staff_email_key', 'Staff', type_='unique')
    op.drop_index('ix_Staff_token', table_name='Staff')
    op.drop_column('Staff', 'password')
    op.drop_column('Staff', 'email')
    op.drop_column('Staff', 'token')
    op.drop_column('Staff', 'token_expiration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Staff', sa.Column('token_expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Staff', sa.Column('token', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('Staff', sa.Column('email', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('Staff', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_index('ix_Staff_token', 'Staff', ['token'], unique=True)
    op.create_unique_constraint('Staff_email_key', 'Staff', ['email'])
    op.drop_index(op.f('ix_User_token'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
