"""add ClientMobileSettings table

Revision ID: 854e2c7c8928
Revises: 65f48672909f
Create Date: 2020-12-16 14:21:08.030651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854e2c7c8928'
down_revision = '65f48672909f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClientMobileSettings',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('use_24_hour_clock', sa.Boolean(), nullable=True),
    sa.Column('date_format', sa.String(), nullable=True),
    sa.Column('include_timezone', sa.Boolean(), nullable=True),
    sa.Column('biometrics_setup', sa.Boolean(), nullable=True),
    sa.Column('timezone_tracking', sa.Boolean(), nullable=True),
    sa.Column('is_right_handed', sa.Boolean(), nullable=True),
    sa.Column('display_middle_name', sa.Boolean(), nullable=True),
    sa.Column('enable_push_notifications', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClientMobileSettings')
    # ### end Alembic commands ###
