"""blood_test_assessment_ranges

Revision ID: 8aa1864e8f00
Revises: c629447e4622
Create Date: 2020-10-15 13:05:33.793926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8aa1864e8f00'
down_revision = 'c629447e4622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MedicalBloodTestResultTypes', sa.Column('normal_max', sa.Float(), nullable=True))
    op.add_column('MedicalBloodTestResultTypes', sa.Column('normal_min', sa.Float(), nullable=True))
    op.add_column('MedicalBloodTestResultTypes', sa.Column('optimal_max', sa.Float(), nullable=True))
    op.add_column('MedicalBloodTestResultTypes', sa.Column('optimal_min', sa.Float(), nullable=True))
    op.add_column('MedicalBloodTestResultTypes', sa.Column('unit', sa.String(), nullable=True))

    op.add_column('MedicalBloodTestResults', sa.Column('evaluation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('MedicalBloodTestResultTypes', 'unit')
    op.drop_column('MedicalBloodTestResultTypes', 'optimal_min')
    op.drop_column('MedicalBloodTestResultTypes', 'optimal_max')
    op.drop_column('MedicalBloodTestResultTypes', 'normal_min')
    op.drop_column('MedicalBloodTestResultTypes', 'normal_max')

    op.drop_column('MedicalBloodTestResults', 'evaluation')
    # ### end Alembic commands ###
