"""Added RegisteredFacilities table

Revision ID: 8ed3e7c53642
Revises: cc90212de393
Create Date: 2020-09-15 11:59:09.657213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed3e7c53642'
down_revision = 'cc90212de393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RegisteredFacilities',
    sa.Column('facility_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('facility_name', sa.String(), nullable=False),
    sa.Column('facility_address', sa.String(), nullable=False),
    sa.Column('modobio_facility', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('facility_id'),
    sa.UniqueConstraint('facility_address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RegisteredFacilities')
    # ### end Alembic commands ###
