"""Remove grant_token from WearablesOura

Revision ID: 9b92a2be034e
Revises: 3cb25c724f84
Create Date: 2020-09-25 18:08:25.599981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b92a2be034e'
down_revision = '3cb25c724f84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WearablesOura', 'grant_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WearablesOura', sa.Column('grant_token', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
