"""Added ClientInfo membersince

Revision ID: a081b9a9c586
Revises: 9d7bf561a158
Create Date: 2020-09-17 16:00:49.726531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a081b9a9c586'
down_revision = '9d7bf561a158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClientInfo', sa.Column('membersince', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClientInfo', 'membersince')
    # ### end Alembic commands ###
