"""add goals and drinks lookup tables

Revision ID: a183f99bc243
Revises: f3bb1b358d75
Create Date: 2020-12-02 15:37:25.087865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a183f99bc243'
down_revision = 'f3bb1b358d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LookupGoals',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('LookupDrinks',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('drink_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('primary_goal_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['primary_goal_id'], ['LookupGoals.goal_id'], ),
    sa.PrimaryKeyConstraint('drink_id')
    )
    op.create_table('LookupDrinkIngredients',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('is_primary_ingredient', sa.Boolean(), nullable=True),
    sa.Column('is_key_additive', sa.Boolean(), nullable=True),
    sa.Column('ingredient_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['LookupDrinks.drink_id'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LookupDrinkIngredients')
    op.drop_table('LookupDrinks')
    op.drop_table('LookupGoals')
    # ### end Alembic commands ###
