"""empty message

Revision ID: ba27d3dde483
Revises: 98f59f69d103
Create Date: 2020-09-09 14:59:04.991532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba27d3dde483'
down_revision = '98f59f69d103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MedicalImaging',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=1024), nullable=True),
    sa.Column('image_date', sa.Date(), nullable=True),
    sa.Column('image_type', sa.String(length=1024), nullable=True),
    sa.Column('image_read', sa.Text(), nullable=True),
    sa.Column('medical_imaging_clinic_info', sa.Text(), nullable=True),
    sa.Column('image_cpt_code', sa.String(length=1024), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='MedicalHistory_clientid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MedicalImaging')
    # ### end Alembic commands ###
