""" 
New fitness questionnaire table

Revision ID: c9c14471cbd4
Revises: 2c861c33474f
Create Date: 2020-08-28 11:54:21.179330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c14471cbd4'
down_revision = '2c861c33474f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrainerFitnessQuestionnaire',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('physical_goals', sa.ARRAY(sa.String()), server_default="{'other'}", nullable=False),
    sa.Column('physical_goals_other', sa.String(), nullable=True),
    sa.Column('physical_goals_notes', sa.String(), nullable=True),
    sa.Column('current_fitness_level', sa.Integer(), nullable=True),
    sa.Column('goal_fitness_level', sa.Integer(), nullable=True),
    sa.Column('trainer_expectation', sa.String(), server_default='other', nullable=False),
    sa.Column('trainer_expectation_other', sa.String(), nullable=True),
    sa.Column('obstacles_likely', sa.Boolean(), nullable=False),
    sa.Column('obstacles_expected', sa.String(), nullable=True),
    sa.Column('lifestyle_goals', sa.ARRAY(sa.String()), server_default="{'other'}", nullable=False),
    sa.Column('lifestyle_goals_other', sa.String(), nullable=True),
    sa.Column('lifestyle_goals_notes', sa.String(), nullable=True),
    sa.Column('sleep_hours', sa.String(), nullable=True),
    sa.Column('sleep_quality_level', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('stress_sources', sa.ARRAY(sa.String()), server_default="{'other'}", nullable=False),
    sa.Column('stress_sources_other', sa.String(), nullable=True),
    sa.Column('stress_sources_notes', sa.String(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('libido_level', sa.Integer(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='fitness_questionnaire_clientid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrainerFitnessQuestionnaire')
    # ### end Alembic commands ###
