""" Creates Medical Blood Chemistry CMP Table

Revision ID: d6c482ee1b12
Revises: 98f59f69d103
Create Date: 2020-09-04 12:20:26.140819

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6c482ee1b12'
down_revision = '98f59f69d103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MedicalBloodChemistryCMP',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('glucose', sa.Float(), nullable=True),
    sa.Column('sodium', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('carbon_dioxide', sa.Float(), nullable=True),
    sa.Column('chloride', sa.Float(), nullable=True),
    sa.Column('magnesium', sa.Float(), nullable=True),
    sa.Column('calcium', sa.Float(), nullable=True),
    sa.Column('phosphorus', sa.Float(), nullable=True),
    sa.Column('uric_acid', sa.Float(), nullable=True),
    sa.Column('bun', sa.Float(), nullable=True),
    sa.Column('creatinine', sa.Float(), nullable=True),
    sa.Column('ast', sa.Float(), nullable=True),
    sa.Column('alt', sa.Float(), nullable=True),
    sa.Column('alk_phophatase', sa.Float(), nullable=True),
    sa.Column('bilirubin', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('albumin', sa.Float(), nullable=True),
    sa.Column('globulin', sa.Float(), nullable=True),
    sa.Column('bunByAlbumin', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='MedicalBloodChemistryCMP_clientid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MedicalBloodChemistryCMP')
    # ### end Alembic commands ###
