"""Added MedicalBloodChemistryLipids table

Revision ID: da5eae0870b7
Revises: d306fec9e8f2
Create Date: 2020-09-09 10:12:32.256737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5eae0870b7'
down_revision = 'd306fec9e8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MedicalBloodChemistryLipids',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('cholesterol_total', sa.Float(), nullable=True),
    sa.Column('cholesterol_ldl', sa.Float(), nullable=True),
    sa.Column('cholesterol_hdl', sa.Float(), nullable=True),
    sa.Column('triglycerides', sa.Float(), nullable=True),
    sa.Column('cholesterol_over_hdl', sa.Float(), nullable=True),
    sa.Column('triglycerides_over_hdl', sa.Float(), nullable=True),
    sa.Column('ldl_over_hdl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='BloodLipids_clientid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MedicalBloodChemistryLipids')
    # ### end Alembic commands ###
