"""Add FreeStyle CGM table

Revision ID: dce299726f19
Revises: 9887fc6db28e
Create Date: 2020-09-16 12:13:51.482233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dce299726f19'
down_revision = '9887fc6db28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WearablesFreeStyle',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('timestamps', postgresql.ARRAY(sa.DateTime(), dimensions=2), nullable=True),
    sa.Column('glucose', postgresql.ARRAY(sa.Float(), dimensions=2), nullable=True),
    sa.Column('activation_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )

    # This is a manual addition. Cannot update existing table with data
    # and add a boolean column with nullable = False. Throws error:
    #   sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation)
    #   column "has_freestyle" contains null values
    op.add_column('Wearables', sa.Column('has_freestyle', sa.Boolean(), default=False, nullable=True))
    op.execute('UPDATE "Wearables" SET has_freestyle = false')
    op.alter_column('Wearables', 'has_freestyle', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Wearables', 'has_freestyle')
    op.drop_table('WearablesFreeStyle')
    # ### end Alembic commands ###
