"""updates to fitness questionnaire

Revision ID: ee9599aef3bc
Revises: f400f854d46d
Create Date: 2020-10-12 11:37:03.845796

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee9599aef3bc'
down_revision = 'f400f854d46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrainerFitnessQuestionnaire', 'confidence_level')
    op.drop_column('TrainerFitnessQuestionnaire', 'obstacles_expected')
    op.drop_column('TrainerFitnessQuestionnaire', 'obstacles_likely')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrainerFitnessQuestionnaire', sa.Column('obstacles_likely', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('TrainerFitnessQuestionnaire', sa.Column('obstacles_expected', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('TrainerFitnessQuestionnaire', sa.Column('confidence_level', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
