"""Adds Medical Imaging Table

Revision ID: f8906e35ca68
Revises: d6c482ee1b12
Create Date: 2020-09-10 17:12:08.259200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8906e35ca68'
down_revision = 'd6c482ee1b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MedicalImaging',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clientid', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=1024), nullable=True),
    sa.Column('image_date', sa.Date(), nullable=True),
    sa.Column('image_type', sa.String(length=1024), nullable=True),
    sa.Column('image_read', sa.Text(), nullable=True),
    sa.Column('medical_imaging_clinic_info', sa.Text(), nullable=True),
    sa.Column('image_cpt_code', sa.String(length=1024), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clientid'], ['ClientInfo.clientid'], name='MedicalImaging_clientid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MedicalImaging')
    # ### end Alembic commands ###
