"""adjust chessboard fields

Revision ID: fbedc9d658e6
Revises: 5216c031bfd8
Create Date: 2020-08-04 11:53:57.746132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbedc9d658e6'
down_revision = '5216c031bfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PTChessboard', sa.Column('co2_tolerance', sa.Integer(), nullable=True))
    op.add_column('PTChessboard', sa.Column('isa_movement', sa.String(length=24), nullable=True))
    op.drop_column('PTChessboard', 'isa_dynamic')
    op.drop_column('PTChessboard', 'isa_right')
    op.drop_column('PTChessboard', 'isa_left')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PTChessboard', sa.Column('isa_left', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('PTChessboard', sa.Column('isa_right', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('PTChessboard', sa.Column('isa_dynamic', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('PTChessboard', 'isa_movement')
    op.drop_column('PTChessboard', 'co2_tolerance')
    # ### end Alembic commands ###
