"""Added requestor id and deleted id to UserRemovalRequests

Revision ID: ffe929556680
Revises: 0e0b2fb1fdf8
Create Date: 2020-12-03 10:39:20.387508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe929556680'
down_revision = '0e0b2fb1fdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserRemovalRequests', sa.Column('deleted_user_id', sa.Integer(), nullable=False))
    op.add_column('UserRemovalRequests', sa.Column('requesting_user_id', sa.Integer(), nullable=False))
    op.drop_constraint('UserRemovalRequests_user_id_fkey', 'UserRemovalRequests', type_='foreignkey')
    op.create_foreign_key(None, 'UserRemovalRequests', 'User', ['deleted_user_id'], ['user_id'])
    op.create_foreign_key(None, 'UserRemovalRequests', 'User', ['requesting_user_id'], ['user_id'])
    op.drop_column('UserRemovalRequests', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserRemovalRequests', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'UserRemovalRequests', type_='foreignkey')
    op.drop_constraint(None, 'UserRemovalRequests', type_='foreignkey')
    op.create_foreign_key('UserRemovalRequests_user_id_fkey', 'UserRemovalRequests', 'User', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('UserRemovalRequests', 'requesting_user_id')
    op.drop_column('UserRemovalRequests', 'deleted_user_id')
    # ### end Alembic commands ###
