"""clientinfo add goal remove record locator id

Revision ID: 05a64546124b
Revises: 854e2c7c8928
Create Date: 2020-12-18 11:45:13.998836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a64546124b'
down_revision = '854e2c7c8928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClientInfo', sa.Column('primary_goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ClientInfo', 'LookupGoals', ['primary_goal_id'], ['goal_id'], ondelete='CASCADE')
    op.drop_column('ClientInfo', 'record_locator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ClientInfo', type_='foreignkey')
    op.drop_column('ClientInfo', 'primary_goal_id')
    # ### end Alembic commands ###
