"""1.0.4 Migration

Revision ID: 89a011cf13b8
Revises: 26dd92d10189
Create Date: 2022-05-27 12:05:01.141935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a011cf13b8'
down_revision = '26dd92d10189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TelehealthBookings', 'external_booking_id', new_column_name='uid')
    op.add_column('TelehealthBookings', sa.Column('staff_calendar_id', sa.Integer(), nullable=True))
    op.create_foreign_key('telehealthbookings_staff_calendar_id_fkey', 'TelehealthBookings', 'StaffCalendarEvents', ['staff_calendar_id'], ['idx'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TelehealthBookings', 'uid', new_column_name='external_booking_id')
    op.drop_constraint('telehealthbookings_staff_calendar_id_fkey', 'TelehealthBookings', type_='foreignkey')
    op.drop_column('TelehealthBookings', 'staff_calendar_id')
    # ### end Alembic commands ###
