"""Remove CountriesOfOperation, LookupTelehealthSessionCosts, add min/max to SystemTelehealthSessionCosts

Revision ID: e1758adc8839
Revises: 73f1c4845245
Create Date: 2021-04-01 11:32:25.914825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1758adc8839'
down_revision = '73f1c4845245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LookupTelehealthSessionCost')
    op.drop_table('SystemTelehealthSessionCosts')
    op.create_table('SystemTelehealthSessionCosts',
    sa.Column('cost_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('profession_type', sa.String(), nullable=False),
    sa.Column('session_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('session_min_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('session_max_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.UniqueConstraint('country', 'profession_type'),
    sa.PrimaryKeyConstraint('cost_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SystemTelehealthSessionCosts'),
    op.create_table('SystemTelehealthSessionCosts',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('profession_type', sa.String(), nullable=False),
    sa.Column('session_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['territory_id'], ['LookupCountriesOfOperations.idx'], ),
    sa.PrimaryKeyConstraint('territory_id', 'profession_type')
    )
    op.create_table('LookupTelehealthSessionCost',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('idx', sa.INTEGER(), server_default=sa.text('nextval(\'"LookupTelehealthSessionCost_idx_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('profession_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('territory', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('session_max_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('session_min_cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('idx', name='LookupTelehealthSessionCost_pkey')
    )
    # ### end Alembic commands ###
