"""add practitioner credentials

Revision ID: b76c62d0757d
Revises: fedd846deffe
Create Date: 2021-08-19 09:53:30.121504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76c62d0757d'
down_revision = 'fedd846deffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PractitionerCredentials',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('credential_type', sa.String(), nullable=True),
    sa.Column('credentials', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('want_to_practice', sa.Boolean(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['LookupCountriesOfOperations.idx'], ),
    sa.ForeignKeyConstraint(['role_id'], ['StaffRoles.idx'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PractitionerCredentials')
    # ### end Alembic commands ###
