"""ehr authorization revert

Revision ID: d4e1d0d3d43c
Revises: 6320015a4b80
Create Date: 2021-07-26 16:23:18.020010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4e1d0d3d43c'
down_revision = '386b0092f0a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ClientEHRPageAuthorizations')
    op.drop_column('ClientClinicalCareTeam', 'team_member_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClientClinicalCareTeam', sa.Column('team_member_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('ClientEHRPageAuthorizations',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=True),
    sa.Column('idx', sa.INTEGER(), server_default=sa.text('nextval(\'"ClientEHRPageAuthorizations_idx_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('team_member_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_group_id'], ['LookupEHRPages.resource_group_id'], name='ClientEHRPageAuthorizations_resource_group_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_member_user_id'], ['User.user_id'], name='ClientEHRPageAuthorizations_team_member_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='ClientEHRPageAuthorizations_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx', name='ClientEHRPageAuthorizations_pkey'),
    sa.UniqueConstraint('user_id', 'team_member_user_id', 'resource_group_id', name='ehr_page_auth_unique_resource_user_team_member_ids')
    )
    # ### end Alembic commands ###
