"""add reference to TelehealthBookings

Revision ID: 02793bda3302
Revises: d7cf0daaee91
Create Date: 2021-04-15 14:19:13.371995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02793bda3302'
down_revision = '60a0292ebacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TelehealthChatRooms', sa.Column('booking_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'TelehealthChatRooms', 'TelehealthBookings', ['booking_id'], ['idx'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TelehealthChatRooms', type_='foreignkey')
    op.drop_column('TelehealthChatRooms', 'booking_id')
    # ### end Alembic commands ###
