"""Add duration & medical_gender fields to TelehealthBookings

Revision ID: eb7f1d60c891
Revises: c537565e285f
Create Date: 2021-10-04 11:17:38.794086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7f1d60c891'
down_revision = 'c537565e285f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ClientInfo', 'street',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=70),
               existing_nullable=True)
    op.alter_column('ClientInfo', 'city',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=35),
               existing_nullable=True)
    op.add_column('TelehealthBookings', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('TelehealthBookings', sa.Column('medical_gender_preference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TelehealthBookings', 'medical_gender_preference')
    op.drop_column('TelehealthBookings', 'duration')
    op.alter_column('ClientInfo', 'city',
               existing_type=sa.String(length=35),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('ClientInfo', 'street',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
