"""overhaul user delete

Revision ID: d50eb8c50cc8
Revises: 10d6092db940
Create Date: 2022-02-17 11:51:56.799317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50eb8c50cc8'
down_revision = '10d6092db940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserRemovalRequests', sa.Column('removal_type', sa.String(), nullable=True))
    op.add_column('User', sa.Column('was_staff', sa.Boolean(), default=False))
    op.drop_constraint('PaymentHistory_booking_id_fkey', 'PaymentHistory', type_='foreignkey')
    op.create_foreign_key(None, 'PaymentHistory', 'TelehealthBookings', ['booking_id'], ['idx'], ondelete='SET NULL')
    op.alter_column('User', 'was_staff',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserRemovalRequests', 'removal_type')
    op.drop_column('User', 'was_staff')
    op.alter_column('User', 'was_staff',
           existing_type=sa.BOOLEAN(),
           nullable=True)
    op.drop_constraint(None, 'PaymentHistory', type_='foreignkey')
    op.create_foreign_key('PaymentHistory_booking_id_fkey', 'PaymentHistory', 'TelehealthBookings', ['booking_id'], ['idx'])
    # ### end Alembic commands ###
