"""Add unique contraint to ClientClinicalCareTeam table.

Revision ID: 8bf3a7337331
Revises: d4e1d0d3d43c
Create Date: 2021-07-30 16:03:35.157697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf3a7337331'
down_revision = 'd4e1d0d3d43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ClientClinicalCareTeam', ['user_id', 'team_member_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ClientClinicalCareTeam', type_='unique')
    # ### end Alembic commands ###
