"""add duration and gender to telehealthqueue table

Revision ID: adc8d825d0cf
Revises: 362e86dd4157
Create Date: 2021-02-24 09:03:15.060626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc8d825d0cf'
down_revision = '362e86dd4157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TelehealthQueueClientPool', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('TelehealthQueueClientPool', sa.Column('medical_gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TelehealthQueueClientPool', 'medical_gender')
    op.drop_column('TelehealthQueueClientPool', 'duration')
    # ### end Alembic commands ###
