"""Add ios_product_id to LookupSubscriptions

Revision ID: 28f6800e6909
Revises: f9ed26de0007
Create Date: 2022-01-21 14:53:06.784280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f6800e6909'
down_revision = '6b322c92d9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LookupSubscriptions', sa.Column('ios_product_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LookupSubscriptions', 'ios_product_id')
    # ### end Alembic commands ###
