"""Add VoIP columns to push notification registration table.

Revision ID: df485c66a11a
Revises: dfb42380a67f
Create Date: 2021-05-28 15:21:01.831981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df485c66a11a'
down_revision = 'dfb42380a67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('NotificationsPushRegistration', sa.Column('device_voip_token', sa.String(length=1024), nullable=True))
    op.add_column('NotificationsPushRegistration', sa.Column('voip_arn', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('NotificationsPushRegistration', 'voip_arn')
    op.drop_column('NotificationsPushRegistration', 'device_voip_token')
    # ### end Alembic commands ###
