"""Creating ClientMobileSettings and UserRemovalRequests tables

Revision ID: 91bf7a4c4aba
Revises: c187e142e6a4
Create Date: 2021-01-06 14:19:26.978795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91bf7a4c4aba'
down_revision = 'c187e142e6a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClientMobileSettings',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('use_24_hour_clock', sa.Boolean(), nullable=True),
    sa.Column('date_format', sa.String(), nullable=True),
    sa.Column('include_timezone', sa.Boolean(), nullable=True),
    sa.Column('biometrics_setup', sa.Boolean(), nullable=True),
    sa.Column('timezone_tracking', sa.Boolean(), nullable=True),
    sa.Column('is_right_handed', sa.Boolean(), nullable=True),
    sa.Column('display_middle_name', sa.Boolean(), nullable=True),
    sa.Column('enable_push_notifications', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('UserRemovalRequests',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.drop_table('ClientRemovalRequests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClientRemovalRequests',
    sa.Column('idx', sa.INTEGER(), server_default=sa.text('nextval(\'"ClientRemovalRequests_idx_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='ClientRemovalRequests_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx', name='ClientRemovalRequests_pkey')
    )
    op.drop_table('UserRemovalRequests')
    op.drop_table('ClientMobileSettings')
    # ### end Alembic commands ###
