"""Deprecates background color and symbol color cols in LookupNotifications table


Revision ID: 6c03f711be26
Revises: f137d07c16ea
Create Date: 2022-04-29 11:37:48.374408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c03f711be26'
down_revision = 'f137d07c16ea'
branch_labels = None
depends_on = None


# Deprecates background color and symbol color cols in LookupNotifications table
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('LookupNotifications', 'background_color')
    op.drop_column('LookupNotifications', 'symbol_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LookupNotifications', sa.Column('symbol_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('LookupNotifications', sa.Column('background_color', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
