"""Change MedicalSurgeries.client_user_id to user_id

Revision ID: 9e0726f03478
Revises: ab7bdaa5a9f0
Create Date: 2021-04-02 08:52:25.450512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0726f03478'
down_revision = '37f095432926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MedicalSurgeries', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('MedicalSurgeries_client_user_id_fkey', 'MedicalSurgeries', type_='foreignkey')
    op.create_foreign_key(None, 'MedicalSurgeries', 'User', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('MedicalSurgeries', 'client_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MedicalSurgeries', sa.Column('client_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'MedicalSurgeries', type_='foreignkey')
    op.create_foreign_key('MedicalSurgeries_client_user_id_fkey', 'MedicalSurgeries', 'User', ['client_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('MedicalSurgeries', 'user_id')
    # ### end Alembic commands ###
