"""Allow NULL for granter_id on StaffRoles to prevent bootstrapping loop when adding staff users to the database.

Revision ID: 735d55e685ea
Revises: 5cd302ce16c2
Create Date: 2021-10-13 17:07:27.194229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735d55e685ea'
down_revision = '5cd302ce16c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('StaffRoles', 'granter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('StaffRoles', 'granter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
