"""add ClientRaceAndEthnicity table

Revision ID: 02d7ab692d7d
Revises: a587a776c819
Create Date: 2021-05-18 16:49:25.271324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d7ab692d7d'
down_revision = 'a587a776c819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ClientRaceAndEthnicity',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_client_mother', sa.Boolean(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['LookupRaces.race_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.drop_constraint('ClientInfo_race_id_fkey', 'ClientInfo', type_='foreignkey')
    op.drop_column('ClientInfo', 'race_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClientInfo', sa.Column('race_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ClientInfo_race_id_fkey', 'ClientInfo', 'LookupRaces', ['race_id'], ['race_id'])
    op.drop_table('ClientRaceAndEthnicity')
    # ### end Alembic commands ###
