"""Adding deleted flag to user table

Revision ID: 2aaaf9e33e1a
Revises: f948a2a5e22a
Create Date: 2021-01-25 16:06:15.811561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aaaf9e33e1a'
down_revision = 'f948a2a5e22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'deleted')
    # ### end Alembic commands ###
