"""add StaffProfile profile_picture

Revision ID: e29540378366
Revises: dd2617890bfd
Create Date: 2021-05-12 18:52:14.154663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29540378366'
down_revision = 'dd2617890bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StaffProfile', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('StaffProfile', 'profile_picture')
    # ### end Alembic commands ###
