"""empty message

Revision ID: 6c37b6174bcf
Revises: b26e574b59f8
Create Date: 2023-06-08 16:10:09.535730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c37b6174bcf'
down_revision = 'ad69ba8f705b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organizations',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('organization_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('max_admins', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    # regenerated in following migration
    # sa.ForeignKeyConstraint(['owner'], ['OrganizationAdmins.admin_id'], ondelete='RESTRICT', deferrable=True),
    sa.PrimaryKeyConstraint('organization_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('OrganizationMembers',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('user_id', 'organization_id')
    )
    op.create_table('OrganizationAdmins',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['OrganizationMembers.member_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['Organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('member_id', 'organization_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Organizations')
    op.drop_table('OrganizationMembers')
    op.drop_table('OrganizationAdmins')
    # ### end Alembic commands ###
