"""add reporter_id to MedicalBloodPressures

Revision ID: ad0512b79f09
Revises: df485c66a11a
Create Date: 2021-06-01 11:06:32.119491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0512b79f09'
down_revision = 'df485c66a11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('MedicalBloodPressures', sa.Column('reporter_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'MedicalBloodPressures', 'User', ['reporter_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'MedicalBloodPressures', type_='foreignkey')
    op.drop_column('MedicalBloodPressures', 'reporter_id')
    # ### end Alembic commands ###
