"""Add (staff|client)_account_closed_reason to UserLogin.

Revision ID: db3492c66548
Revises: 6c03f711be26
Create Date: 2022-04-25 14:31:28.094232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3492c66548'
down_revision = '6c03f711be26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserLogin', sa.Column('staff_account_closed_reason', sa.String(length=500), nullable=True))
    op.add_column('UserLogin', sa.Column('client_account_closed_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserLogin', 'client_account_closed_reason')
    op.drop_column('UserLogin', 'staff_account_closed_reason')
    # ### end Alembic commands ###
