"""update payment tables

Revision ID: 1774bd66de00
Revises: c8e9cff31caa
Create Date: 2021-10-25 14:44:55.892437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1774bd66de00'
down_revision = 'c8e9cff31caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PaymentHistory', sa.Column('booking_id', sa.Integer(), nullable=True))
    op.add_column('PaymentHistory', sa.Column('voided', sa.Boolean(), nullable=True))
    op.add_column('PaymentHistory', sa.Column('void_reason', sa.String(), nullable=True))
    op.add_column('PaymentHistory', sa.Column('void_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'PaymentHistory', 'TelehealthBookings', ['booking_id'], ['idx'])
    op.add_column('PaymentRefunds', sa.Column('refund_transaction_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PaymentRefunds', 'refund_transaction_id')
    op.drop_constraint(None, 'PaymentHistory', type_='foreignkey')
    op.drop_column('PaymentHistory', 'void_id')
    op.drop_column('PaymentHistory', 'void_reason')
    op.drop_column('PaymentHistory', 'voided')
    op.drop_column('PaymentHistory', 'booking_id')
    # ### end Alembic commands ###
