"""adding payment and location to client queue

Revision ID: dffa8a5a3136
Revises: 8f546d475e7a
Create Date: 2021-06-30 08:54:57.169102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffa8a5a3136'
down_revision = '8f546d475e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TelehealthBookingDetails_location_id_fkey', 'TelehealthBookingDetails', type_='foreignkey')
    op.drop_column('TelehealthBookingDetails', 'location_id')
    op.add_column('TelehealthBookings', sa.Column('client_location_id', sa.Integer(), nullable=False))
    op.add_column('TelehealthBookings', sa.Column('payment_method_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'TelehealthBookings', 'PaymentMethods', ['payment_method_id'], ['idx'])
    op.create_foreign_key(None, 'TelehealthBookings', 'LookupTerritoriesofOperation', ['client_location_id'], ['idx'])
    op.add_column('TelehealthQueueClientPool', sa.Column('location_id', sa.Integer(), nullable=False))
    op.add_column('TelehealthQueueClientPool', sa.Column('payment_method_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'TelehealthQueueClientPool', 'PaymentMethods', ['payment_method_id'], ['idx'])
    op.create_foreign_key(None, 'TelehealthQueueClientPool', 'LookupTerritoriesofOperation', ['location_id'], ['idx'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TelehealthQueueClientPool', type_='foreignkey')
    op.drop_constraint(None, 'TelehealthQueueClientPool', type_='foreignkey')
    op.drop_column('TelehealthQueueClientPool', 'payment_method_id')
    op.drop_column('TelehealthQueueClientPool', 'location_id')
    op.drop_constraint(None, 'TelehealthBookings', type_='foreignkey')
    op.drop_constraint(None, 'TelehealthBookings', type_='foreignkey')
    op.drop_column('TelehealthBookings', 'payment_method_id')
    op.drop_column('TelehealthBookings', 'client_location_id')
    op.add_column('TelehealthBookingDetails', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('TelehealthBookingDetails_location_id_fkey', 'TelehealthBookingDetails', 'LookupTerritoriesofOperation', ['location_id'], ['idx'])
    # ### end Alembic commands ###
