"""overhaul blood test system

Revision ID: 6b322c92d9a2
Revises: f9ed26de0007
Create Date: 2022-01-19 15:46:36.828993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b322c92d9a2'
down_revision = 'f9ed26de0007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('LookupBloodTestRanges', 'modobio_test_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('MedicalBloodTestResults', sa.Column('modobio_test_code', sa.String(), nullable=True))
    op.add_column('MedicalBloodTestResults', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('MedicalBloodTestResults', sa.Column('race', sa.String(), nullable=True))
    op.add_column('MedicalBloodTestResults', sa.Column('menstrual_cycle', sa.String(), nullable=True))
    op.add_column('MedicalBloodTestResults', sa.Column('biological_sex_male', sa.Boolean(), nullable=True))
    op.alter_column('MedicalBloodTestResults', 'result_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('MedicalBloodTestResults_result_id_fkey', 'MedicalBloodTestResults', type_='foreignkey')
    op.create_foreign_key(None, 'MedicalBloodTestResults', 'MedicalBloodTestResultTypes', ['result_id'], ['result_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'MedicalBloodTestResults', 'LookupBloodTests', ['modobio_test_code'], ['modobio_test_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'MedicalBloodTestResults', type_='foreignkey')
    op.drop_constraint(None, 'MedicalBloodTestResults', type_='foreignkey')
    op.create_foreign_key('MedicalBloodTestResults_result_id_fkey', 'MedicalBloodTestResults', 'MedicalBloodTestResultTypes', ['result_id'], ['result_id'], ondelete='CASCADE')
    op.alter_column('MedicalBloodTestResults', 'result_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('MedicalBloodTestResults', 'biological_sex_male')
    op.drop_column('MedicalBloodTestResults', 'menstrual_cycle')
    op.drop_column('MedicalBloodTestResults', 'race')
    op.drop_column('MedicalBloodTestResults', 'age')
    op.drop_column('MedicalBloodTestResults', 'modobio_test_code')
    op.alter_column('LookupBloodTestRanges', 'modobio_test_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
