"""drop phone number unique constraint

Revision ID: c708e6669220
Revises: 5ad075e390c4
Create Date: 2021-11-29 17:34:01.345956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c708e6669220'
down_revision = '5ad075e390c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('User_phone_number_key', 'User', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('User_phone_number_key', 'User', ['phone_number'])
    # ### end Alembic commands ###
