"""Add Apple Watch

Revision ID: 86e0a19b9cf0
Revises: a5868270b3cd
Create Date: 2021-03-25 15:59:24.485749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e0a19b9cf0'
down_revision = 'a5868270b3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Wearables', sa.Column(
        'has_applewatch',
        sa.Boolean(),
        server_default='f',
        nullable=True
    ))
    op.add_column('Wearables', sa.Column(
        'registered_applewatch',
        sa.Boolean(),
        server_default='f',
        nullable=True
    ))
    op.alter_column('Wearables', 'has_applewatch',
        existing_type=sa.BOOLEAN(),
        nullable=False
    )
    op.alter_column('Wearables', 'registered_applewatch',
        existing_type=sa.BOOLEAN(),
        nullable=False
    )
    op.alter_column('Wearables', 'has_oura',
        existing_type=sa.BOOLEAN(),
        server_default='f'
    )
    op.alter_column('Wearables', 'registered_oura',
        existing_type=sa.BOOLEAN(),
        server_default='f'
    )
    op.alter_column('Wearables', 'has_fitbit',
        existing_type=sa.BOOLEAN(),
        server_default='f'
    )
    op.alter_column('Wearables', 'registered_fitbit',
        existing_type=sa.BOOLEAN(),
        server_default='f'
    )
    op.alter_column('Wearables', 'has_freestyle',
        existing_type=sa.BOOLEAN(),
        server_default='f'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Wearables', 'registered_applewatch')
    op.drop_column('Wearables', 'has_applewatch')
    op.alter_column('Wearables', 'has_oura',
        existing_type=sa.BOOLEAN(),
        server_default=None
    )
    op.alter_column('Wearables', 'registered_oura',
        existing_type=sa.BOOLEAN(),
        server_default=None
    )
    op.alter_column('Wearables', 'has_fitbit',
        existing_type=sa.BOOLEAN(),
        server_default=None
    )
    op.alter_column('Wearables', 'registered_fitbit',
        existing_type=sa.BOOLEAN(),
        server_default=None
    )
    op.alter_column('Wearables', 'has_freestyle',
        existing_type=sa.BOOLEAN(),
        server_default=None
    )
    # ### end Alembic commands ###
