
"""empty message

Revision ID: 6be0e73cb0cc
Revises: 89a011cf13b8
Create Date: 2022-09-28 18:37:57.970898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be0e73cb0cc'
down_revision = '89a011cf13b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('gender', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'gender')
    # ### end Alembic commands ###