"""Changed staff_user_id to user_id d in StaffRecentClients

Revision ID: fdc34165d9bc
Revises: 3c8640f8727f
Create Date: 2021-01-04 13:35:47.555237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdc34165d9bc'
down_revision = '3c8640f8727f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StaffRecentClients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('StaffRecentClients_staff_user_id_fkey', 'StaffRecentClients', type_='foreignkey')
    op.create_foreign_key(None, 'StaffRecentClients', 'User', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('StaffRecentClients', 'staff_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('StaffRecentClients', sa.Column('staff_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'StaffRecentClients', type_='foreignkey')
    op.create_foreign_key('StaffRecentClients_staff_user_id_fkey', 'StaffRecentClients', 'User', ['staff_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('StaffRecentClients', 'user_id')
    # ### end Alembic commands ###
