"""add LookupMacroGoals table

Revision ID: dfb42380a67f
Revises: d2b96b6c933c
Create Date: 2021-05-24 11:09:37.473958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb42380a67f'
down_revision = 'd2b96b6c933c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LookupMacroGoals',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.add_column('ClientInfo', sa.Column('primary_macro_goal_id', sa.Integer(), nullable=True))
    op.add_column('ClientInfo', sa.Column('primary_goal_description', sa.String(length=300), nullable=True))
    op.create_foreign_key(None, 'ClientInfo', 'LookupMacroGoals', ['primary_macro_goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LookupMacroGoals')
    op.drop_constraint(None, 'ClientInfo', type_='foreignkey')
    op.drop_column('ClientInfo', 'primary_macro_goal_id')
    op.drop_column('ClientInfo', 'primary_goal_description')
    # ### end Alembic commands ###
