"""add LookupCurrencyTypes table

Revision ID: 1757ded21a69
Revises: eee19bdb0e06
Create Date: 2021-06-25 11:44:07.189589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1757ded21a69'
down_revision = 'eee19bdb0e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LookupCurrencies',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('symbol_and_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.add_column('SystemTelehealthSessionCosts', sa.Column('currency_id', sa.Integer(), nullable=False))
    op.drop_constraint('telehealth_costs_unique_resource_country_profession', 'SystemTelehealthSessionCosts', type_='unique')
    op.create_unique_constraint('telehealth_costs_unique_resource_currency_id_profession', 'SystemTelehealthSessionCosts', ['currency_id', 'profession_type'])
    op.create_foreign_key(None, 'SystemTelehealthSessionCosts', 'LookupCurrencies', ['currency_id'], ['idx'])
    op.drop_column('SystemTelehealthSessionCosts', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SystemTelehealthSessionCosts', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'SystemTelehealthSessionCosts', type_='foreignkey')
    op.drop_constraint('telehealth_costs_unique_resource_currency_id_profession', 'SystemTelehealthSessionCosts', type_='unique')
    op.create_unique_constraint('telehealth_costs_unique_resource_country_profession', 'SystemTelehealthSessionCosts', ['country', 'profession_type'])
    op.drop_column('SystemTelehealthSessionCosts', 'currency_id')
    op.drop_table('LookupCurrencies')
    # ### end Alembic commands ###
