"""staff availability timezone

Add timezone field to staff availability and telehealth bookings

Revision ID: 2d4844f4d4ec
Revises: df485c66a11a
Create Date: 2021-06-02 04:36:25.153151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4844f4d4ec'
down_revision = 'e024249f8efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TelehealthStaffAvailability', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('TelehealthBookings', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TelehealthStaffAvailability', 'timezone')
    op.drop_column('TelehealthBookings', 'timezone')
    # ### end Alembic commands ###
