"""Add lookup table for blood glucose ranges

Revision ID: 508113125af2
Revises: b50b55dbf985
Create Date: 2022-12-08 12:58:06.049264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508113125af2'
down_revision = 'b50b55dbf985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LookupBloodGlucoseRanges',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modobio_test_code', sa.String(), nullable=False),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('hypoglycemia_max', sa.Float(), nullable=True),
    sa.Column('normal_min', sa.Float(), nullable=True),
    sa.Column('normal_max', sa.Float(), nullable=True),
    sa.Column('prediabetic_min', sa.Float(), nullable=True),
    sa.Column('prediabetic_max', sa.Float(), nullable=True),
    sa.Column('diabetic_min', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['modobio_test_code'], ['LookupBloodTests.modobio_test_code'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LookupBloodGlucoseRanges')
    # ### end Alembic commands ###
