"""Add LookupBloodTests and LookupBloodTestRanges

Revision ID: f9ed26de0007
Revises: 3aba8c40d22f
Create Date: 2022-01-11 16:23:07.779982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ed26de0007'
down_revision = '3aba8c40d22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LookupBloodTests',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('modobio_test_code', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('quest_test_code', sa.String(), nullable=True),
    sa.Column('cpt_test_code', sa.String(), nullable=True),
    sa.Column('panel_display_name', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('modobio_test_code')
    )
    op.create_table('LookupBloodTestRanges',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modobio_test_code', sa.String(), nullable=False),
    sa.Column('biological_sex_male', sa.Boolean(), nullable=True),
    sa.Column('menstrual_cycle', sa.String(), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('ratio', sa.String(), nullable=True),
    sa.Column('critical_min', sa.Float(), nullable=True),
    sa.Column('ref_min', sa.Float(), nullable=True),
    sa.Column('ref_max', sa.Float(), nullable=True),
    sa.Column('critical_max', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['modobio_test_code'], ['LookupBloodTests.modobio_test_code'], ),
    sa.ForeignKeyConstraint(['race_id'], ['LookupRaces.race_id'], ),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LookupBloodTestRanges')
    op.drop_table('LookupBloodTests')
    # ### end Alembic commands ###
