"""TelehealthBookings external booking id

Revision ID: 0bebaad7e4a1
Revises: 74355bf4dc85
Create Date: 2021-09-02 17:17:25.091449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bebaad7e4a1'
down_revision = '74355bf4dc85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TelehealthBookings', sa.Column('external_booking_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TelehealthBookings', 'external_booking_id')
    # ### end Alembic commands ###
