"""update notifications table

Revision ID: 83eabfbaecf4
Revises: 25d16cc47dfb
Create Date: 2022-02-28 15:26:07.460460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83eabfbaecf4'
down_revision = '25d16cc47dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notifications', sa.Column('severity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Notifications', 'LookupNotificationSeverity', ['severity_id'], ['idx'], ondelete='SET NULL')
    op.drop_column('Notifications', 'action')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notifications', sa.Column('action', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Notifications', type_='foreignkey')
    op.drop_column('Notifications', 'severity_id')
    # ### end Alembic commands ###
