"""empty message

Revision ID: b26e574b59f8
Revises: 73b9e8b8b4aa
Create Date: 2023-05-24 12:41:40.940764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b26e574b59f8"
down_revision = "73b9e8b8b4aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("LookupSubscriptions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("google_product_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("LookupSubscriptions", schema=None) as batch_op:
        batch_op.drop_column("google_product_id")

    # ### end Alembic commands ###
