"""updated userSubscriptions table

Revision ID: e21ae83791f6
Revises: ac16cd39251f
Create Date: 2021-02-02 13:40:18.750798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e21ae83791f6'
down_revision = 'ac16cd39251f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserSubscriptions', sa.Column('subscription_status', sa.String(), nullable=True))
    op.add_column('UserSubscriptions', sa.Column('subscription_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'UserSubscriptions', 'LookupSubscriptions', ['subscription_type_id'], ['sub_id'])
    op.drop_column('UserSubscriptions', 'subscription_type')
    op.drop_column('UserSubscriptions', 'subscription_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserSubscriptions', sa.Column('subscription_rate', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('UserSubscriptions', sa.Column('subscription_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'UserSubscriptions', type_='foreignkey')
    op.drop_column('UserSubscriptions', 'subscription_type_id')
    op.drop_column('UserSubscriptions', 'subscription_status')
    # ### end Alembic commands ###
