"""Add Cardholder name to PaymentMethods

Revision ID: 5ad075e390c4
Revises: cc0d0aaeb7d3
Create Date: 2021-11-18 12:30:59.873999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ad075e390c4'
down_revision = 'cc0d0aaeb7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PaymentMethods', sa.Column('cardholder_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PaymentMethods', 'cardholder_name')
    # ### end Alembic commands ###
