"""App store integration. UserSubscriptions fields

Revision ID: 10d6092db940
Revises: 1079f0374c0d
Create Date: 2022-02-10 10:30:09.520354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d6092db940'
down_revision = '1079f0374c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserSubscriptions', sa.Column('last_checked_date', sa.DateTime(), nullable=True))
    op.add_column('UserSubscriptions', sa.Column('apple_original_transaction_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserSubscriptions', 'apple_original_transaction_id')
    op.drop_column('UserSubscriptions', 'last_checked_date')
    # ### end Alembic commands ###
