"""allow null for th details images

Revision ID: 0ddd60d24ee3
Revises: 0a7df014fea4
Create Date: 2022-03-29 12:37:37.986907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ddd60d24ee3'
down_revision = '0a7df014fea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TelehealthBookingDetails', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=1024)),
               server_default='{}')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TelehealthBookingDetails', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=1024)))
    # ### end Alembic commands ###
