"""Add Persona Type and drop Time to Live in Notifications table

Revision ID: 1c0a83fb65e5
Revises: db3492c66548
Create Date: 2022-05-10 15:10:15.558183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0a83fb65e5'
down_revision = 'db3492c66548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notifications', sa.Column('persona_type', sa.String(length=10), nullable=True))
    op.drop_column('Notifications', 'time_to_live')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notifications', sa.Column('time_to_live', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Notifications', 'persona_type')
    # ### end Alembic commands ###
