"""add affiliation_user_id to PractitionerOrganizationAffiliation

Revision ID: 10bc815f355e
Revises: 1ab60df860cc
Create Date: 2021-08-12 15:10:20.035382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10bc815f355e'
down_revision = 'fc7f98a1735b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PractitionerOrganizationAffiliation', sa.Column('affiliate_user_id', sa.String(), nullable=True))
    op.alter_column('User', 'email',
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=75),
            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PractitionerOrganizationAffiliation', 'affiliate_user_id')
    op.alter_column('User', 'email',
            existing_type=sa.String(length=75),
            type_=sa.VARCHAR(length=50),
            existing_nullable=True)
    # ### end Alembic commands ###
