"""empty message

Revision ID: 4f3bbbdd8742
Revises: 1f5fc0ac6048
Create Date: 2022-06-10 11:48:04.209967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f3bbbdd8742'
down_revision = '1f5fc0ac6048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LookupDrinkIngredients')
    op.drop_table('ClientAssignedDrinks')
    op.drop_table('LookupDrinks')
    op.drop_column('ClientIndividualContract', 'drinks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClientIndividualContract', sa.Column('drinks', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('ClientAssignedDrinks',
    sa.Column('idx', sa.INTEGER(), server_default=sa.text('nextval(\'"ClientAssignedDrinks_idx_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drink_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['LookupDrinks.drink_id'], name='ClientAssignedDrinks_drink_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='ClientAssignedDrinks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx', name='ClientAssignedDrinks_pkey')
    )
    op.create_table('LookupDrinks',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=True),
    sa.Column('drink_id', sa.INTEGER(), server_default=sa.text('nextval(\'"LookupDrinks_drink_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('primary_goal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['primary_goal_id'], ['LookupGoals.goal_id'], name='LookupDrinks_primary_goal_id_fkey'),
    sa.PrimaryKeyConstraint('drink_id', name='LookupDrinks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('LookupDrinkIngredients',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=True),
    sa.Column('idx', sa.INTEGER(), server_default=sa.text('nextval(\'"LookupDrinkIngredients_idx_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('drink_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_primary_ingredient', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_key_additive', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ingredient_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['LookupDrinks.drink_id'], name='LookupDrinkIngredients_drink_id_fkey'),
    sa.PrimaryKeyConstraint('idx', name='LookupDrinkIngredients_pkey')
    )
    # ### end Alembic commands ###
