"""Telehealth meeting rooms table

Revision ID: 362e86dd4157
Revises: a659b7e8875c
Create Date: 2021-02-18 10:32:06.183300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362e86dd4157'
down_revision = '9d3ec8dfc66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TelehealthMeetingRooms',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('room_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_name', sa.String(), nullable=True),
    sa.Column('client_user_id', sa.Integer(), nullable=False),
    sa.Column('staff_user_id', sa.Integer(), nullable=False),
    sa.Column('client_access_token', sa.String(), nullable=True),
    sa.Column('staff_access_token', sa.String(), nullable=True),
    sa.Column('room_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_user_id'], ['User.user_id'], ),
    sa.ForeignKeyConstraint(['staff_user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TelehealthMeetingRooms')
    # ### end Alembic commands ###
