"""empty message

Revision ID: c299cfc94eab
Revises: 3a9e0a00c75f
Create Date: 2023-06-07 17:31:28.392139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c299cfc94eab'
down_revision = '3a9e0a00c75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Admins', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['member_id', 'organization_id'])
        batch_op.create_foreign_key(None, 'Members', ['member_id'], ['member_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'Organizations', ['organization_id'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('Members', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id', 'organization_id'])
        batch_op.create_foreign_key(None, 'Organizations', ['organization_id'], ['uuid'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('Organizations', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Admins', ['owner'], ['admin_id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Organizations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Admins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
