"""Add client goal remove record locator id

Revision ID: 1bbb031b9213
Revises: 651640b15d14
Create Date: 2021-01-11 09:56:11.793785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbb031b9213'
down_revision = '651640b15d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClientInfo', sa.Column('primary_goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ClientInfo', 'LookupGoals', ['primary_goal_id'], ['goal_id'], ondelete='CASCADE')
    op.drop_column('ClientInfo', 'record_locator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClientInfo', sa.Column('record_locator_id', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ClientInfo', type_='foreignkey')
    op.drop_column('ClientInfo', 'primary_goal_id')
    # ### end Alembic commands ###
