"""Add StaffOffices table

Revision ID: 1ab60df860cc
Revises: a2b1226364ee
Create Date: 2021-08-06 12:31:11.962106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab60df860cc'
down_revision = 'a2b1226364ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('StaffOffices',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=35), nullable=True),
    sa.Column('state', sa.String(length=35), nullable=True),
    sa.Column('zipcode', sa.String(length=20), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_type', sa.String(length=7), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['LookupCountriesOfOperations.idx'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.add_column('LookupTerritoriesofOperation', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'LookupTerritoriesofOperation', 'LookupCountriesOfOperations', ['country_id'], ['idx'])
    op.drop_column('LookupTerritoriesofOperation', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LookupTerritoriesofOperation', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'LookupTerritoriesofOperation', type_='foreignkey')
    op.drop_column('LookupTerritoriesofOperation', 'country_id')
    op.drop_table('StaffOffices')
    # ### end Alembic commands ###
