"""a ClientClinicalCareTeam is_temporary field

Revision ID: d2b96b6c933c
Revises: 02d7ab692d7d
Create Date: 2021-05-25 15:24:35.686999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b96b6c933c'
down_revision = '02d7ab692d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ClientClinicalCareTeam', sa.Column('is_temporary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClientClinicalCareTeam', 'is_temporary')
    # ### end Alembic commands ###
