"""Add UserPendingEmailVerifications table

Revision ID: 7703a1c1f50e
Revises: f56c6155f65c
Create Date: 2021-04-15 14:21:04.742896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7703a1c1f50e'
down_revision = 'f56c6155f65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserPendingEmailVerifications',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('code', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.alter_column('SystemTelehealthSessionCosts', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('telehealth_costs_unique_resource_country_profession', 'SystemTelehealthSessionCosts', ['country', 'profession_type'])
    op.drop_constraint('SystemTelehealthSessionCosts_country_profession_type_key', 'SystemTelehealthSessionCosts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('SystemTelehealthSessionCosts_country_profession_type_key', 'SystemTelehealthSessionCosts', ['country', 'profession_type'])
    op.drop_constraint('telehealth_costs_unique_resource_country_profession', 'SystemTelehealthSessionCosts', type_='unique')
    op.alter_column('SystemTelehealthSessionCosts', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('UserPendingEmailVerifications')
    # ### end Alembic commands ###
