"""Change string length limit for tokens

Revision ID: a5868270b3cd
Revises: 9bd25635f1e6
Create Date: 2021-03-01 15:52:01.345670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5868270b3cd'
down_revision = '9bd25635f1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('WearablesFitbit', 'access_token',
               existing_type=sa.String(50),
               type_=sa.String(512))
    op.alter_column('WearablesFitbit', 'refresh_token',
               existing_type=sa.String(50),
               type_=sa.String(512))
    op.alter_column('WearablesFitbit', 'oauth_state',
               existing_type=sa.String(50),
               type_=sa.String(512))
    op.alter_column('WearablesOura', 'access_token',
               existing_type=sa.String(50),
               type_=sa.String(512))
    op.alter_column('WearablesOura', 'refresh_token',
               existing_type=sa.String(50),
               type_=sa.String(512))
    op.alter_column('WearablesOura', 'oauth_state',
               existing_type=sa.String(50),
               type_=sa.String(512))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('WearablesFitbit', 'access_token',
               existing_type=sa.String(512),
               type_=sa.String(50))
    op.alter_column('WearablesFitbit', 'refresh_token',
               existing_type=sa.String(512),
               type_=sa.String(50))
    op.alter_column('WearablesFitbit', 'oauth_state',
               existing_type=sa.String(512),
               type_=sa.String(50))
    op.alter_column('WearablesOura', 'access_token',
               existing_type=sa.String(512),
               type_=sa.String(50))
    op.alter_column('WearablesOura', 'refresh_token',
               existing_type=sa.String(512),
               type_=sa.String(50))
    op.alter_column('WearablesOura', 'oauth_state',
               existing_type=sa.String(512),
               type_=sa.String(50))
    # ### end Alembic commands ###
