"""look up telehealth session duration

Revision ID: 5a0ae7ad37d1
Revises: 86e0a19b9cf0
Create Date: 2021-01-05 18:05:14.288685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0ae7ad37d1'
down_revision = '86e0a19b9cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LookupTelehealthSessionDuration',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_duration', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LookupTelehealthSessionDuration')
    # ### end Alembic commands ###
