"""Add lookup table for CGM reference range support

Revision ID: f5c0431a97e0
Revises: 508113125af2
Create Date: 2023-01-04 13:03:28.457217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5c0431a97e0"
down_revision = "508113125af2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "LookupCGMDemographics",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("clock_timestamp()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("clock_timestamp()"),
            nullable=True,
        ),
        sa.Column("idx", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("demographic", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("idx"),
        sa.UniqueConstraint("demographic"),
    )
    op.create_table(
        "LookupBloodGlucoseCGMRanges",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("clock_timestamp()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("clock_timestamp()"),
            nullable=True,
        ),
        sa.Column("idx", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("demographic_id", sa.Integer(), nullable=True),
        sa.Column("classification", sa.String(), nullable=True),
        sa.Column("min_mg_dL", sa.Float(), nullable=True),
        sa.Column("max_mg_dL", sa.Float(), nullable=True),
        sa.Column("max_mmol_L", sa.Float(), nullable=True),
        sa.Column("min_mmol_L", sa.Float(), nullable=True),
        sa.Column("min_percent_in", sa.Float(), nullable=True),
        sa.Column("max_percent_in", sa.Float(), nullable=True),
        sa.Column("min_time_in", sa.Float(), nullable=True),
        sa.Column("max_time_in", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["demographic_id"],
            ["LookupCGMDemographics.idx"],
        ),
        sa.PrimaryKeyConstraint("idx"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("LookupBloodGlucoseCGMRanges")
    op.drop_table("LookupCGMDemographics")
    # ### end Alembic commands ###
