"""add PaymentStatus table

Revision ID: 57c9bb87eb62
Revises: dffa8a5a3136
Create Date: 2021-07-08 14:38:38.923903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c9bb87eb62'
down_revision = 'dffa8a5a3136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PaymentStatus',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_present_status', sa.String(), nullable=True),
    sa.Column('current_transaction_status_code', sa.String(), nullable=True),
    sa.Column('original_transaction_id', sa.String(), nullable=True),
    sa.Column('original_transaction_status_code', sa.String(), nullable=True),
    sa.Column('payment_transaction_id', sa.String(), nullable=True),
    sa.Column('request_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('save_on_file_transaction_id', sa.String(), nullable=True),
    sa.Column('transaction_action', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PaymentStatus')
    # ### end Alembic commands ###
