"""Add timezone fields for telehealth availability and bookings

Revision ID: 45f124410e19
Revises: e024249f8efe
Create Date: 2021-06-07 10:11:53.930032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f124410e19'
down_revision = '5fb1aae9de2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TelehealthBookings', sa.Column('client_timezone', sa.String(), nullable=True))
    op.add_column('TelehealthBookings', sa.Column('staff_timezone', sa.String(), nullable=True))
    op.add_column('TelehealthStaffAvailability', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('TelehealthBookings', sa.Column('target_date_utc', sa.Date(), nullable=True))
    op.add_column('TelehealthBookings', sa.Column('booking_window_id_start_time_utc', sa.Integer(), nullable=False))
    op.add_column('TelehealthBookings', sa.Column('booking_window_id_end_time_utc', sa.Integer(), nullable=False))
    op.create_foreign_key('lookup_booking_time_inc_utc_end_fk', 'TelehealthBookings', 'LookupBookingTimeIncrements', ['booking_window_id_end_time_utc'], ['idx'], ondelete='CASCADE')
    op.create_foreign_key('lookup_booking_time_inc_utc_start_fk', 'TelehealthBookings', 'LookupBookingTimeIncrements', ['booking_window_id_start_time_utc'], ['idx'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TelehealthStaffAvailability', 'timezone')
    op.drop_column('TelehealthBookings', 'staff_timezone')
    op.drop_column('TelehealthBookings', 'client_timezone')
    op.drop_constraint('lookup_booking_time_inc_utc_end_fk', 'TelehealthBookings', type_='foreignkey')
    op.drop_constraint('lookup_booking_time_inc_utc_start_fk', 'TelehealthBookings', type_='foreignkey')
    op.drop_column('TelehealthBookings', 'booking_window_id_end_time_utc')
    op.drop_column('TelehealthBookings', 'booking_window_id_start_time_utc')
    op.drop_column('TelehealthBookings', 'target_date_utc')
    # ### end Alembic commands ###
