"""remove PaymentFailedTransactions

Revision ID: a6162914753b
Revises: 0bebaad7e4a1
Create Date: 2021-09-28 15:06:16.471030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a6162914753b'
down_revision = '0bebaad7e4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PaymentFailedTransactions')
    op.add_column('TelehealthBookings', sa.Column('charged', sa.Boolean(), nullable=True))
    op.drop_column('TelehealthBookings', 'is_paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TelehealthBookings', sa.Column('is_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('TelehealthBookings', 'charged')
    op.create_table('PaymentFailedTransactions',
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('clock_timestamp()'), autoincrement=False, nullable=True),
    sa.Column('idx', sa.INTEGER(), server_default=sa.text('nextval(\'"PaymentFailedTransactions_idx_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='PaymentFailedTransactions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx', name='PaymentFailedTransactions_pkey')
    )
    # ### end Alembic commands ###
