"""add availability horizon th setting

Revision ID: 011fba7ccb8b
Revises: 3fb9896eadc9
Create Date: 2022-06-08 18:24:05.166416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011fba7ccb8b'
down_revision = '3fb9896eadc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TelehealthStaffSettings', sa.Column('availability_horizon', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TelehealthStaffSettings', 'availability_horizon')
    # ### end Alembic commands ###
