"""Adds email_reminded field to TelehealthBookings table

Revision ID: 72d5e26b8641
Revises: f81e7cbdab82
Create Date: 2022-11-08 12:28:50.785179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d5e26b8641'
<<<<<<<< HEAD:migrations/versions/release-1.2.1_11_72d5e26b8641_adds_email_reminded_field_to_.py
down_revision = 'f81e7cbdab82'
========
down_revision = '3669c98b6396'
>>>>>>>> release-1.2.1:migrations/versions/release-1.2.1_09_72d5e26b8641_adds_email_reminded_field_to_.py
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TelehealthBookings', sa.Column('email_reminded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TelehealthBookings', 'email_reminded')
    # ### end Alembic commands ###
