"""lookup professional confirmation window

Revision ID: e8cb26a9db4e
Revises: a45013f3958d
Create Date: 2021-02-06 03:47:18.789911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8cb26a9db4e'
down_revision = '758e1ddc5e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LookupProfessionalAppointmentConfirmationWindow',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('confirmation_window', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LookupProfessionalAppointmentConfirmationWindow')
    # ### end Alembic commands ###
