"""Add PaymentFailedTransaction table

Revision ID: e75d9850a95a
Revises: 2f4b0cc846a3
Create Date: 2021-09-01 14:10:30.958419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75d9850a95a'
down_revision = '2f4b0cc846a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PaymentFailedTransactions',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    op.add_column('PaymentMethods', sa.Column('expiration', sa.String(), nullable=True))
    op.add_column('TelehealthBookings', sa.Column('is_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TelehealthBookings', 'is_paid')
    op.drop_column('PaymentMethods', 'expiration')
    op.drop_table('PaymentFailedTransactions')
    # ### end Alembic commands ###
