"""Rename TelehealthBookings.external_booking_id to uid

Revision ID: e920d4450a4d
Revises: 0ddd60d24ee3
Create Date: 2022-05-27 12:05:01.141935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e920d4450a4d'
down_revision = '0ddd60d24ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TelehealthBookings', 'external_booking_id', new_column_name='uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TelehealthBookings', 'uid', new_column_name='external_booking_id')
    # ### end Alembic commands ###
