"""Change default to server_default for booleans on User table.
Additionally, make User.deleted nullable.

Revision ID: 08e4c602da79
Revises: 735d55e685ea
Create Date: 2021-10-13 17:21:53.585265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e4c602da79'
down_revision = '735d55e685ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'is_staff',
                existing_type=sa.BOOLEAN,
                server_default='false')
    op.alter_column('User', 'is_client',
                existing_type=sa.BOOLEAN,
                server_default='false')
    op.alter_column('User', 'deleted',
                existing_type=sa.BOOLEAN,
                server_default='false',
                nullable=False)
    op.alter_column('User', 'is_internal',
                existing_type=sa.BOOLEAN,
                server_default='false')
    op.alter_column('User', 'email_verified',
                existing_type=sa.BOOLEAN,
                server_default='false')
    op.alter_column('User', 'biological_sex_male',
                existing_type=sa.BOOLEAN,
                server_default='false')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'is_staff',
                existing_type=sa.BOOLEAN,
                default=False)
    op.alter_column('User', 'is_client',
                existing_type=sa.BOOLEAN,
                default=False)
    op.alter_column('User', 'deleted',
                existing_type=sa.BOOLEAN,
                default=False,
                nullable=True)
    op.alter_column('User', 'is_internal',
                existing_type=sa.BOOLEAN,
                default=False)
    op.alter_column('User', 'email_verified',
                existing_type=sa.BOOLEAN,
                default=False)
    op.alter_column('User', 'biological_sex_male',
                existing_type=sa.BOOLEAN,
                default=False)
    # ### end Alembic commands ###
