"""Create org models, commented out FK constraint for cycle

Revision ID: 6c37b6174bcf
Revises: b26e574b59f8
Create Date: 2023-06-16 10:37:03.535460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c37b6174bcf'
down_revision = 'b26e574b59f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Organizations',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('organization_uuid', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('max_admins', sa.Integer(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['owner'], ['OrganizationAdmins.user_id'], ondelete='RESTRICT', deferrable=True),
    sa.PrimaryKeyConstraint('organization_uuid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('OrganizationMembers',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_uuid'], ['Organizations.organization_uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id', 'organization_uuid')
    )
    op.create_table('OrganizationAdmins',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('clock_timestamp()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_uuid'], ['Organizations.organization_uuid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['OrganizationMembers.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id', 'organization_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('OrganizationAdmins')
    op.drop_table('OrganizationMembers')
    op.drop_table('Organizations')
    # ### end Alembic commands ###
