"""add emergency numbers table

Revision ID: 0a355c29b670
Revises: c4c5c968b777
Create Date: 2021-03-13 16:06:54.773527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a355c29b670'
down_revision = 'c4c5c968b777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LookupEmergencyNumbers',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('continent', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('idx', 'code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LookupEmergencyNumbers')
    # ### end Alembic commands ###
