"""Adds email_reminded field to TelehealthBookings table

Revision ID: 72d5e26b8641
Revises: a2cd76a0affa
Create Date: 2022-11-08 12:28:50.785179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d5e26b8641'
down_revision = 'a2cd76a0affa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TelehealthBookings', sa.Column('email_reminded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TelehealthBookings', 'email_reminded')
    # ### end Alembic commands ###
