"""add availability horizon th setting

Revision ID: ff20cb442a77
Revises: 3fb9896eadc9
Create Date: 2022-06-07 11:59:03.888209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff20cb442a77'
down_revision = '3fb9896eadc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TelehealthStaffSettings', sa.Column('availability_horizon', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TelehealthStaffSettings', 'availability_horizon')
    # ### end Alembic commands ###
