"""move dob to user model

Revision ID: 74355bf4dc85
Revises: 10bc815f355e
Create Date: 2021-08-31 01:35:50.309122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '74355bf4dc85'
down_revision = '10bc815f355e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ClientInfo', 'dob')
    op.add_column('User', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'dob')
    op.add_column('ClientInfo', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
