"""Add UserResetPasswordRequestHistory table

Revision ID: 2f4b0cc846a3
Revises: fc7f98a1735b
Create Date: 2021-08-30 15:29:50.436664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4b0cc846a3'
down_revision = 'fc7f98a1735b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserResetPasswordRequestHistory',
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ua_string', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserResetPasswordRequestHistory')
    # ### end Alembic commands ###
