import os
import sys
sys.path.insert(0, os.path.abspath('../src'))

from setuptools_scm import get_version
version = get_version(root='..', relative_to=__file__)
release = version

project = 'Odyssey'
author = 'Zan'

with open('../LICENSE.md') as fh:
    copyright = fh.read().strip()

extensions = [
    # numpydoc syntax
    'sphinx.ext.napoleon',
    # links to other projects
    'sphinx.ext.intersphinx'
]

# Don't use modules.rst and odyssey.rst. They get generated by apidoc,
# but they are too many levels of nesting.
exclude_patterns = [
    'odyssey/odyssey.rst',
    'odyssey/modules.rst',
    'odyssey/odyssey.version.rst',
    '_build',
    'Thumbs.db',
    '.DS_Store'
]

html_theme = 'sphinx_rtd_theme'

napoleon_use_ivar = True
napoleon_use_rtype = False

autodoc_default_options = {
    'no-undoc-members': True,
    'member-order': 'bysource'
}

intersphinx_mapping = {
    'flask': ('https://flask.palletsprojects.com/', None),
    'flask_wtf': ('https://flask-wtf.readthedocs.io/en/stable/', None),
    'python': ('https://docs.python.org/3/', None),
    'sqlalchemy': ('https://docs.sqlalchemy.org/', None),
    'werkzeug': ('https://werkzeug.palletsprojects.com/', None),
    'wtforms': ('https://wtforms.readthedocs.io/', None)
}
