import os
import sys
sys.path.insert(0, os.path.abspath('../src'))

from odyssey.__init__ import __version__

project = 'Odyssey'
author = 'Zan'

with open('../LICENSE.md') as fh:
    copyright = fh.read().strip()

version = __version__
release = version

extensions = [
    # numpydoc syntax
    'sphinx.ext.napoleon',
    # links to other projects
    'sphinx.ext.intersphinx'
]

# Don't use api/modules.rst. It gets generated by apidoc,
# but it's one too many layers of organization.
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    'api/modules.rst'
]

html_theme = 'sphinx_rtd_theme'

napoleon_use_ivar = True
napoleon_use_rtype = False

autodoc_default_options = {
    'no-undoc-members': True
}

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'sqlalchemy': ('https://docs.sqlalchemy.org/', None),
    'werkzeug': ('https://werkzeug.palletsprojects.com/', None),
    'wtforms': ('https://wtforms.readthedocs.io/', None)
}
