import os
import sys
sys.path.insert(0, os.path.abspath('../src'))

from setuptools_scm import get_version

def plain_version(version):
    return 'version: {}'.format(version.tag)

version = get_version(
    root='..',
    relative_to=__file__,
    version_scheme=plain_version,
    local_scheme='no-local-version'
)
release = version

project = 'Odyssey'
author = 'Zan'

with open('../LICENSE.md') as fh:
    copyright = fh.read().strip()

extensions = [
    # numpydoc syntax
    'sphinx.ext.napoleon',
    # links to other projects
    'sphinx.ext.intersphinx'
]

# Don't use the following files that get generated by apidoc.
exclude_patterns = [
    'odyssey/odyssey.rst',
    'odyssey/modules.rst',
    'odyssey/odyssey.forms*',
    'odyssey/odyssey.views*',
    'odyssey/odyssey.version.rst',
    'odyssey/odyssey.run.rst',
    '_build',
    'Thumbs.db',
    '.DS_Store'
]

html_theme = 'sphinx_rtd_theme'

napoleon_use_ivar = True
napoleon_use_rtype = False

autodoc_default_options = {
    'no-undoc-members': True,
    'member-order': 'bysource'
}

intersphinx_mapping = {
    'flask': ('https://flask.palletsprojects.com/', None),
    'flask_migrate': ('https://flask-migrate.readthedocs.io/en/latest/', None),
    'flask_sqlalchemy': ('https://flask-sqlalchemy.palletsprojects.com/', None),
    'flask_wtf': ('https://flask-wtf.readthedocs.io/en/stable/', None),
    'python': ('https://docs.python.org/3/', None),
    'sqlalchemy': ('https://docs.sqlalchemy.org/', None),
    'werkzeug': ('https://werkzeug.palletsprojects.com/', None),
    'whoosh': ('https://whoosh.readthedocs.io/en/latest/', None),
    'wtforms': ('https://wtforms.readthedocs.io/', None)
}
